/*
HDRUK Gateway API

Testing SearchCollectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gatewayapisdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/HDRUK/gateway-api-go-sdk"
)

func Test_gatewayapisdk_SearchCollectionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SearchCollectionsAPIService SearchCollections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SearchCollectionsAPI.SearchCollections(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
