/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// CancerTypeFilterAPIService CancerTypeFilterAPI service
type CancerTypeFilterAPIService service

type ApiGetCancerTypeFilterRequest struct {
	ctx context.Context
	ApiService *CancerTypeFilterAPIService
	filterId string
}

func (r ApiGetCancerTypeFilterRequest) Execute() (*GetCancerTypeFilter200Response, *http.Response, error) {
	return r.ApiService.GetCancerTypeFilterExecute(r)
}

/*
GetCancerTypeFilter Get a single cancer type filter

Returns a single cancer type filter with its children by filter_id

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param filterId Filter ID (e.g., 0_0, 0_0_2_59)
 @return ApiGetCancerTypeFilterRequest
*/
func (a *CancerTypeFilterAPIService) GetCancerTypeFilter(ctx context.Context, filterId string) ApiGetCancerTypeFilterRequest {
	return ApiGetCancerTypeFilterRequest{
		ApiService: a,
		ctx: ctx,
		filterId: filterId,
	}
}

// Execute executes the request
//  @return GetCancerTypeFilter200Response
func (a *CancerTypeFilterAPIService) GetCancerTypeFilterExecute(r ApiGetCancerTypeFilterRequest) (*GetCancerTypeFilter200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetCancerTypeFilter200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CancerTypeFilterAPIService.GetCancerTypeFilter")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/cancer-type-filters/{filter_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"filter_id"+"}", url.PathEscape(parameterValueToString(r.filterId, "filterId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v GetCancerTypeFilter404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetCancerTypeFiltersRequest struct {
	ctx context.Context
	ApiService *CancerTypeFilterAPIService
	parentId *int32
	level *int32
}

// Filter by parent ID
func (r ApiGetCancerTypeFiltersRequest) ParentId(parentId int32) ApiGetCancerTypeFiltersRequest {
	r.parentId = &parentId
	return r
}

// Filter by hierarchy level
func (r ApiGetCancerTypeFiltersRequest) Level(level int32) ApiGetCancerTypeFiltersRequest {
	r.level = &level
	return r
}

func (r ApiGetCancerTypeFiltersRequest) Execute() (*GetCancerTypeFilters200Response, *http.Response, error) {
	return r.ApiService.GetCancerTypeFiltersExecute(r)
}

/*
GetCancerTypeFilters Get all cancer type filters

Returns a hierarchical tree of cancer type filters

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetCancerTypeFiltersRequest
*/
func (a *CancerTypeFilterAPIService) GetCancerTypeFilters(ctx context.Context) ApiGetCancerTypeFiltersRequest {
	return ApiGetCancerTypeFiltersRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetCancerTypeFilters200Response
func (a *CancerTypeFilterAPIService) GetCancerTypeFiltersExecute(r ApiGetCancerTypeFiltersRequest) (*GetCancerTypeFilters200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetCancerTypeFilters200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CancerTypeFilterAPIService.GetCancerTypeFilters")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/cancer-type-filters"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.parentId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "parent_id", r.parentId, "form", "")
	}
	if r.level != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "level", r.level, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
