/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchTeamQuestionBankQuestionsBySection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchTeamQuestionBankQuestionsBySection200Response{}

// FetchTeamQuestionBankQuestionsBySection200Response struct for FetchTeamQuestionBankQuestionsBySection200Response
type FetchTeamQuestionBankQuestionsBySection200Response struct {
	Message *string `json:"message,omitempty"`
	Data []FetchTeamQuestionBankQuestionsBySection200ResponseDataInner `json:"data,omitempty"`
}

// NewFetchTeamQuestionBankQuestionsBySection200Response instantiates a new FetchTeamQuestionBankQuestionsBySection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchTeamQuestionBankQuestionsBySection200Response() *FetchTeamQuestionBankQuestionsBySection200Response {
	this := FetchTeamQuestionBankQuestionsBySection200Response{}
	return &this
}

// NewFetchTeamQuestionBankQuestionsBySection200ResponseWithDefaults instantiates a new FetchTeamQuestionBankQuestionsBySection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchTeamQuestionBankQuestionsBySection200ResponseWithDefaults() *FetchTeamQuestionBankQuestionsBySection200Response {
	this := FetchTeamQuestionBankQuestionsBySection200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) GetData() []FetchTeamQuestionBankQuestionsBySection200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []FetchTeamQuestionBankQuestionsBySection200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) GetDataOk() ([]FetchTeamQuestionBankQuestionsBySection200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []FetchTeamQuestionBankQuestionsBySection200ResponseDataInner and assigns it to the Data field.
func (o *FetchTeamQuestionBankQuestionsBySection200Response) SetData(v []FetchTeamQuestionBankQuestionsBySection200ResponseDataInner) {
	o.Data = v
}

func (o FetchTeamQuestionBankQuestionsBySection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchTeamQuestionBankQuestionsBySection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchTeamQuestionBankQuestionsBySection200Response struct {
	value *FetchTeamQuestionBankQuestionsBySection200Response
	isSet bool
}

func (v NullableFetchTeamQuestionBankQuestionsBySection200Response) Get() *FetchTeamQuestionBankQuestionsBySection200Response {
	return v.value
}

func (v *NullableFetchTeamQuestionBankQuestionsBySection200Response) Set(val *FetchTeamQuestionBankQuestionsBySection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchTeamQuestionBankQuestionsBySection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchTeamQuestionBankQuestionsBySection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchTeamQuestionBankQuestionsBySection200Response(val *FetchTeamQuestionBankQuestionsBySection200Response) *NullableFetchTeamQuestionBankQuestionsBySection200Response {
	return &NullableFetchTeamQuestionBankQuestionsBySection200Response{value: val, isSet: true}
}

func (v NullableFetchTeamQuestionBankQuestionsBySection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchTeamQuestionBankQuestionsBySection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


