/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the UpdateSavedSearches200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSavedSearches200Response{}

// UpdateSavedSearches200Response struct for UpdateSavedSearches200Response
type UpdateSavedSearches200Response struct {
	Message *string `json:"message,omitempty"`
	Data *SavedSearch `json:"data,omitempty"`
}

// NewUpdateSavedSearches200Response instantiates a new UpdateSavedSearches200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSavedSearches200Response() *UpdateSavedSearches200Response {
	this := UpdateSavedSearches200Response{}
	return &this
}

// NewUpdateSavedSearches200ResponseWithDefaults instantiates a new UpdateSavedSearches200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSavedSearches200ResponseWithDefaults() *UpdateSavedSearches200Response {
	this := UpdateSavedSearches200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateSavedSearches200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSavedSearches200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateSavedSearches200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateSavedSearches200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateSavedSearches200Response) GetData() SavedSearch {
	if o == nil || IsNil(o.Data) {
		var ret SavedSearch
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSavedSearches200Response) GetDataOk() (*SavedSearch, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateSavedSearches200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SavedSearch and assigns it to the Data field.
func (o *UpdateSavedSearches200Response) SetData(v SavedSearch) {
	o.Data = &v
}

func (o UpdateSavedSearches200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSavedSearches200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableUpdateSavedSearches200Response struct {
	value *UpdateSavedSearches200Response
	isSet bool
}

func (v NullableUpdateSavedSearches200Response) Get() *UpdateSavedSearches200Response {
	return v.value
}

func (v *NullableUpdateSavedSearches200Response) Set(val *UpdateSavedSearches200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSavedSearches200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSavedSearches200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSavedSearches200Response(val *UpdateSavedSearches200Response) *NullableUpdateSavedSearches200Response {
	return &NullableUpdateSavedSearches200Response{value: val, isSet: true}
}

func (v NullableUpdateSavedSearches200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSavedSearches200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


