/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"time"
)

// checks if the CreateApplications200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplications200ResponseDataInner{}

// CreateApplications200ResponseDataInner struct for CreateApplications200ResponseDataInner
type CreateApplications200ResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	AppId *string `json:"app_id,omitempty"`
	ClientId *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	ImageLink *string `json:"image_link,omitempty"`
	Description *string `json:"description,omitempty"`
	TeamId *int32 `json:"team_id,omitempty"`
	UserId *int32 `json:"user_id,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Permissions []interface{} `json:"permissions,omitempty"`
	Team []interface{} `json:"team,omitempty"`
	User []interface{} `json:"user,omitempty"`
	Notifications []interface{} `json:"notifications,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewCreateApplications200ResponseDataInner instantiates a new CreateApplications200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplications200ResponseDataInner() *CreateApplications200ResponseDataInner {
	this := CreateApplications200ResponseDataInner{}
	return &this
}

// NewCreateApplications200ResponseDataInnerWithDefaults instantiates a new CreateApplications200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplications200ResponseDataInnerWithDefaults() *CreateApplications200ResponseDataInner {
	this := CreateApplications200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CreateApplications200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateApplications200ResponseDataInner) SetName(v string) {
	o.Name = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *CreateApplications200ResponseDataInner) SetAppId(v string) {
	o.AppId = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *CreateApplications200ResponseDataInner) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *CreateApplications200ResponseDataInner) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetImageLink returns the ImageLink field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetImageLink() string {
	if o == nil || IsNil(o.ImageLink) {
		var ret string
		return ret
	}
	return *o.ImageLink
}

// GetImageLinkOk returns a tuple with the ImageLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetImageLinkOk() (*string, bool) {
	if o == nil || IsNil(o.ImageLink) {
		return nil, false
	}
	return o.ImageLink, true
}

// HasImageLink returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasImageLink() bool {
	if o != nil && !IsNil(o.ImageLink) {
		return true
	}

	return false
}

// SetImageLink gets a reference to the given string and assigns it to the ImageLink field.
func (o *CreateApplications200ResponseDataInner) SetImageLink(v string) {
	o.ImageLink = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateApplications200ResponseDataInner) SetDescription(v string) {
	o.Description = &v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetTeamId() int32 {
	if o == nil || IsNil(o.TeamId) {
		var ret int32
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetTeamIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given int32 and assigns it to the TeamId field.
func (o *CreateApplications200ResponseDataInner) SetTeamId(v int32) {
	o.TeamId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *CreateApplications200ResponseDataInner) SetUserId(v int32) {
	o.UserId = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateApplications200ResponseDataInner) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetPermissions() []interface{} {
	if o == nil || IsNil(o.Permissions) {
		var ret []interface{}
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetPermissionsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []interface{} and assigns it to the Permissions field.
func (o *CreateApplications200ResponseDataInner) SetPermissions(v []interface{}) {
	o.Permissions = v
}

// GetTeam returns the Team field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetTeam() []interface{} {
	if o == nil || IsNil(o.Team) {
		var ret []interface{}
		return ret
	}
	return o.Team
}

// GetTeamOk returns a tuple with the Team field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetTeamOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Team) {
		return nil, false
	}
	return o.Team, true
}

// HasTeam returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasTeam() bool {
	if o != nil && !IsNil(o.Team) {
		return true
	}

	return false
}

// SetTeam gets a reference to the given []interface{} and assigns it to the Team field.
func (o *CreateApplications200ResponseDataInner) SetTeam(v []interface{}) {
	o.Team = v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetUser() []interface{} {
	if o == nil || IsNil(o.User) {
		var ret []interface{}
		return ret
	}
	return o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetUserOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given []interface{} and assigns it to the User field.
func (o *CreateApplications200ResponseDataInner) SetUser(v []interface{}) {
	o.User = v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetNotifications() []interface{} {
	if o == nil || IsNil(o.Notifications) {
		var ret []interface{}
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetNotificationsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []interface{} and assigns it to the Notifications field.
func (o *CreateApplications200ResponseDataInner) SetNotifications(v []interface{}) {
	o.Notifications = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CreateApplications200ResponseDataInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *CreateApplications200ResponseDataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *CreateApplications200ResponseDataInner) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplications200ResponseDataInner) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *CreateApplications200ResponseDataInner) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *CreateApplications200ResponseDataInner) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

func (o CreateApplications200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplications200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AppId) {
		toSerialize["app_id"] = o.AppId
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if !IsNil(o.ImageLink) {
		toSerialize["image_link"] = o.ImageLink
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.TeamId) {
		toSerialize["team_id"] = o.TeamId
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.Team) {
		toSerialize["team"] = o.Team
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	return toSerialize, nil
}

type NullableCreateApplications200ResponseDataInner struct {
	value *CreateApplications200ResponseDataInner
	isSet bool
}

func (v NullableCreateApplications200ResponseDataInner) Get() *CreateApplications200ResponseDataInner {
	return v.value
}

func (v *NullableCreateApplications200ResponseDataInner) Set(val *CreateApplications200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplications200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplications200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplications200ResponseDataInner(val *CreateApplications200ResponseDataInner) *NullableCreateApplications200ResponseDataInner {
	return &NullableCreateApplications200ResponseDataInner{value: val, isSet: true}
}

func (v NullableCreateApplications200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplications200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


