/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchAllPublications200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllPublications200Response{}

// FetchAllPublications200Response struct for FetchAllPublications200Response
type FetchAllPublications200Response struct {
	Data []Publication `json:"data,omitempty"`
}

// NewFetchAllPublications200Response instantiates a new FetchAllPublications200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllPublications200Response() *FetchAllPublications200Response {
	this := FetchAllPublications200Response{}
	return &this
}

// NewFetchAllPublications200ResponseWithDefaults instantiates a new FetchAllPublications200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllPublications200ResponseWithDefaults() *FetchAllPublications200Response {
	this := FetchAllPublications200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchAllPublications200Response) GetData() []Publication {
	if o == nil || IsNil(o.Data) {
		var ret []Publication
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllPublications200Response) GetDataOk() ([]Publication, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchAllPublications200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Publication and assigns it to the Data field.
func (o *FetchAllPublications200Response) SetData(v []Publication) {
	o.Data = v
}

func (o FetchAllPublications200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllPublications200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchAllPublications200Response struct {
	value *FetchAllPublications200Response
	isSet bool
}

func (v NullableFetchAllPublications200Response) Get() *FetchAllPublications200Response {
	return v.value
}

func (v *NullableFetchAllPublications200Response) Set(val *FetchAllPublications200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllPublications200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllPublications200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllPublications200Response(val *FetchAllPublications200Response) *NullableFetchAllPublications200Response {
	return &NullableFetchAllPublications200Response{value: val, isSet: true}
}

func (v NullableFetchAllPublications200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllPublications200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


