/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the UpdateReviews200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateReviews200Response{}

// UpdateReviews200Response struct for UpdateReviews200Response
type UpdateReviews200Response struct {
	Message *string `json:"message,omitempty"`
	Data *UpdateReviews200ResponseData `json:"data,omitempty"`
}

// NewUpdateReviews200Response instantiates a new UpdateReviews200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateReviews200Response() *UpdateReviews200Response {
	this := UpdateReviews200Response{}
	return &this
}

// NewUpdateReviews200ResponseWithDefaults instantiates a new UpdateReviews200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateReviews200ResponseWithDefaults() *UpdateReviews200Response {
	this := UpdateReviews200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateReviews200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateReviews200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateReviews200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateReviews200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateReviews200Response) GetData() UpdateReviews200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret UpdateReviews200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateReviews200Response) GetDataOk() (*UpdateReviews200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateReviews200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given UpdateReviews200ResponseData and assigns it to the Data field.
func (o *UpdateReviews200Response) SetData(v UpdateReviews200ResponseData) {
	o.Data = &v
}

func (o UpdateReviews200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateReviews200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableUpdateReviews200Response struct {
	value *UpdateReviews200Response
	isSet bool
}

func (v NullableUpdateReviews200Response) Get() *UpdateReviews200Response {
	return v.value
}

func (v *NullableUpdateReviews200Response) Set(val *UpdateReviews200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateReviews200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateReviews200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateReviews200Response(val *UpdateReviews200Response) *NullableUpdateReviews200Response {
	return &NullableUpdateReviews200Response{value: val, isSet: true}
}

func (v NullableUpdateReviews200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateReviews200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


