/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the UpdateUserHasRolesRequestRoles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserHasRolesRequestRoles{}

// UpdateUserHasRolesRequestRoles struct for UpdateUserHasRolesRequestRoles
type UpdateUserHasRolesRequestRoles struct {
	Read *bool `json:"read,omitempty"`
	Create *bool `json:"create,omitempty"`
}

// NewUpdateUserHasRolesRequestRoles instantiates a new UpdateUserHasRolesRequestRoles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserHasRolesRequestRoles() *UpdateUserHasRolesRequestRoles {
	this := UpdateUserHasRolesRequestRoles{}
	return &this
}

// NewUpdateUserHasRolesRequestRolesWithDefaults instantiates a new UpdateUserHasRolesRequestRoles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserHasRolesRequestRolesWithDefaults() *UpdateUserHasRolesRequestRoles {
	this := UpdateUserHasRolesRequestRoles{}
	return &this
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *UpdateUserHasRolesRequestRoles) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserHasRolesRequestRoles) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *UpdateUserHasRolesRequestRoles) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *UpdateUserHasRolesRequestRoles) SetRead(v bool) {
	o.Read = &v
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *UpdateUserHasRolesRequestRoles) GetCreate() bool {
	if o == nil || IsNil(o.Create) {
		var ret bool
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserHasRolesRequestRoles) GetCreateOk() (*bool, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *UpdateUserHasRolesRequestRoles) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given bool and assigns it to the Create field.
func (o *UpdateUserHasRolesRequestRoles) SetCreate(v bool) {
	o.Create = &v
}

func (o UpdateUserHasRolesRequestRoles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserHasRolesRequestRoles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}
	return toSerialize, nil
}

type NullableUpdateUserHasRolesRequestRoles struct {
	value *UpdateUserHasRolesRequestRoles
	isSet bool
}

func (v NullableUpdateUserHasRolesRequestRoles) Get() *UpdateUserHasRolesRequestRoles {
	return v.value
}

func (v *NullableUpdateUserHasRolesRequestRoles) Set(val *UpdateUserHasRolesRequestRoles) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserHasRolesRequestRoles) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserHasRolesRequestRoles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserHasRolesRequestRoles(val *UpdateUserHasRolesRequestRoles) *NullableUpdateUserHasRolesRequestRoles {
	return &NullableUpdateUserHasRolesRequestRoles{value: val, isSet: true}
}

func (v NullableUpdateUserHasRolesRequestRoles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserHasRolesRequestRoles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


