/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"time"
)

// checks if the FetchAllReviews200ResponseDataInnerUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllReviews200ResponseDataInnerUser{}

// FetchAllReviews200ResponseDataInnerUser struct for FetchAllReviews200ResponseDataInnerUser
type FetchAllReviews200ResponseDataInnerUser struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Firstname *string `json:"firstname,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
	Email *string `json:"email,omitempty"`
	EmailVerifiedAt *int32 `json:"email_verified_at,omitempty"`
	Providerid *string `json:"providerid,omitempty"`
	Provider *string `json:"provider,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewFetchAllReviews200ResponseDataInnerUser instantiates a new FetchAllReviews200ResponseDataInnerUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllReviews200ResponseDataInnerUser() *FetchAllReviews200ResponseDataInnerUser {
	this := FetchAllReviews200ResponseDataInnerUser{}
	return &this
}

// NewFetchAllReviews200ResponseDataInnerUserWithDefaults instantiates a new FetchAllReviews200ResponseDataInnerUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllReviews200ResponseDataInnerUserWithDefaults() *FetchAllReviews200ResponseDataInnerUser {
	this := FetchAllReviews200ResponseDataInnerUser{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetName(v string) {
	o.Name = &v
}

// GetFirstname returns the Firstname field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetFirstname() string {
	if o == nil || IsNil(o.Firstname) {
		var ret string
		return ret
	}
	return *o.Firstname
}

// GetFirstnameOk returns a tuple with the Firstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetFirstnameOk() (*string, bool) {
	if o == nil || IsNil(o.Firstname) {
		return nil, false
	}
	return o.Firstname, true
}

// HasFirstname returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasFirstname() bool {
	if o != nil && !IsNil(o.Firstname) {
		return true
	}

	return false
}

// SetFirstname gets a reference to the given string and assigns it to the Firstname field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetFirstname(v string) {
	o.Firstname = &v
}

// GetLastname returns the Lastname field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetLastname() string {
	if o == nil || IsNil(o.Lastname) {
		var ret string
		return ret
	}
	return *o.Lastname
}

// GetLastnameOk returns a tuple with the Lastname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetLastnameOk() (*string, bool) {
	if o == nil || IsNil(o.Lastname) {
		return nil, false
	}
	return o.Lastname, true
}

// HasLastname returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasLastname() bool {
	if o != nil && !IsNil(o.Lastname) {
		return true
	}

	return false
}

// SetLastname gets a reference to the given string and assigns it to the Lastname field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetLastname(v string) {
	o.Lastname = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetEmail(v string) {
	o.Email = &v
}

// GetEmailVerifiedAt returns the EmailVerifiedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetEmailVerifiedAt() int32 {
	if o == nil || IsNil(o.EmailVerifiedAt) {
		var ret int32
		return ret
	}
	return *o.EmailVerifiedAt
}

// GetEmailVerifiedAtOk returns a tuple with the EmailVerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetEmailVerifiedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.EmailVerifiedAt) {
		return nil, false
	}
	return o.EmailVerifiedAt, true
}

// HasEmailVerifiedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasEmailVerifiedAt() bool {
	if o != nil && !IsNil(o.EmailVerifiedAt) {
		return true
	}

	return false
}

// SetEmailVerifiedAt gets a reference to the given int32 and assigns it to the EmailVerifiedAt field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetEmailVerifiedAt(v int32) {
	o.EmailVerifiedAt = &v
}

// GetProviderid returns the Providerid field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetProviderid() string {
	if o == nil || IsNil(o.Providerid) {
		var ret string
		return ret
	}
	return *o.Providerid
}

// GetProvideridOk returns a tuple with the Providerid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetProvideridOk() (*string, bool) {
	if o == nil || IsNil(o.Providerid) {
		return nil, false
	}
	return o.Providerid, true
}

// HasProviderid returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasProviderid() bool {
	if o != nil && !IsNil(o.Providerid) {
		return true
	}

	return false
}

// SetProviderid gets a reference to the given string and assigns it to the Providerid field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetProviderid(v string) {
	o.Providerid = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetProvider(v string) {
	o.Provider = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerUser) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerUser) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *FetchAllReviews200ResponseDataInnerUser) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

func (o FetchAllReviews200ResponseDataInnerUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllReviews200ResponseDataInnerUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Firstname) {
		toSerialize["firstname"] = o.Firstname
	}
	if !IsNil(o.Lastname) {
		toSerialize["lastname"] = o.Lastname
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.EmailVerifiedAt) {
		toSerialize["email_verified_at"] = o.EmailVerifiedAt
	}
	if !IsNil(o.Providerid) {
		toSerialize["providerid"] = o.Providerid
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	return toSerialize, nil
}

type NullableFetchAllReviews200ResponseDataInnerUser struct {
	value *FetchAllReviews200ResponseDataInnerUser
	isSet bool
}

func (v NullableFetchAllReviews200ResponseDataInnerUser) Get() *FetchAllReviews200ResponseDataInnerUser {
	return v.value
}

func (v *NullableFetchAllReviews200ResponseDataInnerUser) Set(val *FetchAllReviews200ResponseDataInnerUser) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllReviews200ResponseDataInnerUser) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllReviews200ResponseDataInnerUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllReviews200ResponseDataInnerUser(val *FetchAllReviews200ResponseDataInnerUser) *NullableFetchAllReviews200ResponseDataInnerUser {
	return &NullableFetchAllReviews200ResponseDataInnerUser{value: val, isSet: true}
}

func (v NullableFetchAllReviews200ResponseDataInnerUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllReviews200ResponseDataInnerUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


