/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the SearchDataUses200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchDataUses200ResponseDataInner{}

// SearchDataUses200ResponseDataInner struct for SearchDataUses200ResponseDataInner
type SearchDataUses200ResponseDataInner struct {
	Source []SearchDataUses200ResponseDataInnerSourceInner `json:"_source,omitempty"`
	Highlight []SearchDataUses200ResponseDataInnerHighlightInner `json:"highlight,omitempty"`
}

// NewSearchDataUses200ResponseDataInner instantiates a new SearchDataUses200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchDataUses200ResponseDataInner() *SearchDataUses200ResponseDataInner {
	this := SearchDataUses200ResponseDataInner{}
	return &this
}

// NewSearchDataUses200ResponseDataInnerWithDefaults instantiates a new SearchDataUses200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchDataUses200ResponseDataInnerWithDefaults() *SearchDataUses200ResponseDataInner {
	this := SearchDataUses200ResponseDataInner{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SearchDataUses200ResponseDataInner) GetSource() []SearchDataUses200ResponseDataInnerSourceInner {
	if o == nil || IsNil(o.Source) {
		var ret []SearchDataUses200ResponseDataInnerSourceInner
		return ret
	}
	return o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataUses200ResponseDataInner) GetSourceOk() ([]SearchDataUses200ResponseDataInnerSourceInner, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SearchDataUses200ResponseDataInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given []SearchDataUses200ResponseDataInnerSourceInner and assigns it to the Source field.
func (o *SearchDataUses200ResponseDataInner) SetSource(v []SearchDataUses200ResponseDataInnerSourceInner) {
	o.Source = v
}

// GetHighlight returns the Highlight field value if set, zero value otherwise.
func (o *SearchDataUses200ResponseDataInner) GetHighlight() []SearchDataUses200ResponseDataInnerHighlightInner {
	if o == nil || IsNil(o.Highlight) {
		var ret []SearchDataUses200ResponseDataInnerHighlightInner
		return ret
	}
	return o.Highlight
}

// GetHighlightOk returns a tuple with the Highlight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataUses200ResponseDataInner) GetHighlightOk() ([]SearchDataUses200ResponseDataInnerHighlightInner, bool) {
	if o == nil || IsNil(o.Highlight) {
		return nil, false
	}
	return o.Highlight, true
}

// HasHighlight returns a boolean if a field has been set.
func (o *SearchDataUses200ResponseDataInner) HasHighlight() bool {
	if o != nil && !IsNil(o.Highlight) {
		return true
	}

	return false
}

// SetHighlight gets a reference to the given []SearchDataUses200ResponseDataInnerHighlightInner and assigns it to the Highlight field.
func (o *SearchDataUses200ResponseDataInner) SetHighlight(v []SearchDataUses200ResponseDataInnerHighlightInner) {
	o.Highlight = v
}

func (o SearchDataUses200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchDataUses200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["_source"] = o.Source
	}
	if !IsNil(o.Highlight) {
		toSerialize["highlight"] = o.Highlight
	}
	return toSerialize, nil
}

type NullableSearchDataUses200ResponseDataInner struct {
	value *SearchDataUses200ResponseDataInner
	isSet bool
}

func (v NullableSearchDataUses200ResponseDataInner) Get() *SearchDataUses200ResponseDataInner {
	return v.value
}

func (v *NullableSearchDataUses200ResponseDataInner) Set(val *SearchDataUses200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchDataUses200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchDataUses200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchDataUses200ResponseDataInner(val *SearchDataUses200ResponseDataInner) *NullableSearchDataUses200ResponseDataInner {
	return &NullableSearchDataUses200ResponseDataInner{value: val, isSet: true}
}

func (v NullableSearchDataUses200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchDataUses200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


