/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchAliases404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAliases404Response{}

// FetchAliases404Response struct for FetchAliases404Response
type FetchAliases404Response struct {
	Message *string `json:"message,omitempty"`
}

// NewFetchAliases404Response instantiates a new FetchAliases404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAliases404Response() *FetchAliases404Response {
	this := FetchAliases404Response{}
	return &this
}

// NewFetchAliases404ResponseWithDefaults instantiates a new FetchAliases404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAliases404ResponseWithDefaults() *FetchAliases404Response {
	this := FetchAliases404Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchAliases404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAliases404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchAliases404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchAliases404Response) SetMessage(v string) {
	o.Message = &v
}

func (o FetchAliases404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAliases404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableFetchAliases404Response struct {
	value *FetchAliases404Response
	isSet bool
}

func (v NullableFetchAliases404Response) Get() *FetchAliases404Response {
	return v.value
}

func (v *NullableFetchAliases404Response) Set(val *FetchAliases404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAliases404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAliases404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAliases404Response(val *FetchAliases404Response) *NullableFetchAliases404Response {
	return &NullableFetchAliases404Response{value: val, isSet: true}
}

func (v NullableFetchAliases404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAliases404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


