/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchTeamDarApplicationHeader200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchTeamDarApplicationHeader200Response{}

// FetchTeamDarApplicationHeader200Response struct for FetchTeamDarApplicationHeader200Response
type FetchTeamDarApplicationHeader200Response struct {
	Message *string `json:"message,omitempty"`
	Data *FetchTeamDarApplicationHeader200ResponseData `json:"data,omitempty"`
}

// NewFetchTeamDarApplicationHeader200Response instantiates a new FetchTeamDarApplicationHeader200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchTeamDarApplicationHeader200Response() *FetchTeamDarApplicationHeader200Response {
	this := FetchTeamDarApplicationHeader200Response{}
	return &this
}

// NewFetchTeamDarApplicationHeader200ResponseWithDefaults instantiates a new FetchTeamDarApplicationHeader200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchTeamDarApplicationHeader200ResponseWithDefaults() *FetchTeamDarApplicationHeader200Response {
	this := FetchTeamDarApplicationHeader200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchTeamDarApplicationHeader200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchTeamDarApplicationHeader200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchTeamDarApplicationHeader200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchTeamDarApplicationHeader200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchTeamDarApplicationHeader200Response) GetData() FetchTeamDarApplicationHeader200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret FetchTeamDarApplicationHeader200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchTeamDarApplicationHeader200Response) GetDataOk() (*FetchTeamDarApplicationHeader200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchTeamDarApplicationHeader200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FetchTeamDarApplicationHeader200ResponseData and assigns it to the Data field.
func (o *FetchTeamDarApplicationHeader200Response) SetData(v FetchTeamDarApplicationHeader200ResponseData) {
	o.Data = &v
}

func (o FetchTeamDarApplicationHeader200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchTeamDarApplicationHeader200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchTeamDarApplicationHeader200Response struct {
	value *FetchTeamDarApplicationHeader200Response
	isSet bool
}

func (v NullableFetchTeamDarApplicationHeader200Response) Get() *FetchTeamDarApplicationHeader200Response {
	return v.value
}

func (v *NullableFetchTeamDarApplicationHeader200Response) Set(val *FetchTeamDarApplicationHeader200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchTeamDarApplicationHeader200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchTeamDarApplicationHeader200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchTeamDarApplicationHeader200Response(val *FetchTeamDarApplicationHeader200Response) *NullableFetchTeamDarApplicationHeader200Response {
	return &NullableFetchTeamDarApplicationHeader200Response{value: val, isSet: true}
}

func (v NullableFetchTeamDarApplicationHeader200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchTeamDarApplicationHeader200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


