/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchAllProgrammingLanguages200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllProgrammingLanguages200Response{}

// FetchAllProgrammingLanguages200Response struct for FetchAllProgrammingLanguages200Response
type FetchAllProgrammingLanguages200Response struct {
	Message *string `json:"message,omitempty"`
	Data []ProgrammingLanguage `json:"data,omitempty"`
}

// NewFetchAllProgrammingLanguages200Response instantiates a new FetchAllProgrammingLanguages200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllProgrammingLanguages200Response() *FetchAllProgrammingLanguages200Response {
	this := FetchAllProgrammingLanguages200Response{}
	return &this
}

// NewFetchAllProgrammingLanguages200ResponseWithDefaults instantiates a new FetchAllProgrammingLanguages200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllProgrammingLanguages200ResponseWithDefaults() *FetchAllProgrammingLanguages200Response {
	this := FetchAllProgrammingLanguages200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchAllProgrammingLanguages200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllProgrammingLanguages200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchAllProgrammingLanguages200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchAllProgrammingLanguages200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchAllProgrammingLanguages200Response) GetData() []ProgrammingLanguage {
	if o == nil || IsNil(o.Data) {
		var ret []ProgrammingLanguage
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllProgrammingLanguages200Response) GetDataOk() ([]ProgrammingLanguage, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchAllProgrammingLanguages200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ProgrammingLanguage and assigns it to the Data field.
func (o *FetchAllProgrammingLanguages200Response) SetData(v []ProgrammingLanguage) {
	o.Data = v
}

func (o FetchAllProgrammingLanguages200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllProgrammingLanguages200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchAllProgrammingLanguages200Response struct {
	value *FetchAllProgrammingLanguages200Response
	isSet bool
}

func (v NullableFetchAllProgrammingLanguages200Response) Get() *FetchAllProgrammingLanguages200Response {
	return v.value
}

func (v *NullableFetchAllProgrammingLanguages200Response) Set(val *FetchAllProgrammingLanguages200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllProgrammingLanguages200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllProgrammingLanguages200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllProgrammingLanguages200Response(val *FetchAllProgrammingLanguages200Response) *NullableFetchAllProgrammingLanguages200Response {
	return &NullableFetchAllProgrammingLanguages200Response{value: val, isSet: true}
}

func (v NullableFetchAllProgrammingLanguages200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllProgrammingLanguages200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


