/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchDurById200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchDurById200Response{}

// FetchDurById200Response struct for FetchDurById200Response
type FetchDurById200Response struct {
	Message *string `json:"message,omitempty"`
	Data []Dur `json:"data,omitempty"`
}

// NewFetchDurById200Response instantiates a new FetchDurById200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchDurById200Response() *FetchDurById200Response {
	this := FetchDurById200Response{}
	return &this
}

// NewFetchDurById200ResponseWithDefaults instantiates a new FetchDurById200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchDurById200ResponseWithDefaults() *FetchDurById200Response {
	this := FetchDurById200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchDurById200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchDurById200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchDurById200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchDurById200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchDurById200Response) GetData() []Dur {
	if o == nil || IsNil(o.Data) {
		var ret []Dur
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchDurById200Response) GetDataOk() ([]Dur, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchDurById200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Dur and assigns it to the Data field.
func (o *FetchDurById200Response) SetData(v []Dur) {
	o.Data = v
}

func (o FetchDurById200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchDurById200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchDurById200Response struct {
	value *FetchDurById200Response
	isSet bool
}

func (v NullableFetchDurById200Response) Get() *FetchDurById200Response {
	return v.value
}

func (v *NullableFetchDurById200Response) Set(val *FetchDurById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchDurById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchDurById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchDurById200Response(val *FetchDurById200Response) *NullableFetchDurById200Response {
	return &NullableFetchDurById200Response{value: val, isSet: true}
}

func (v NullableFetchDurById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchDurById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


