/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the VerifySecondaryEmail200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifySecondaryEmail200Response{}

// VerifySecondaryEmail200Response struct for VerifySecondaryEmail200Response
type VerifySecondaryEmail200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewVerifySecondaryEmail200Response instantiates a new VerifySecondaryEmail200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifySecondaryEmail200Response() *VerifySecondaryEmail200Response {
	this := VerifySecondaryEmail200Response{}
	return &this
}

// NewVerifySecondaryEmail200ResponseWithDefaults instantiates a new VerifySecondaryEmail200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifySecondaryEmail200ResponseWithDefaults() *VerifySecondaryEmail200Response {
	this := VerifySecondaryEmail200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *VerifySecondaryEmail200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySecondaryEmail200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *VerifySecondaryEmail200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *VerifySecondaryEmail200Response) SetMessage(v string) {
	o.Message = &v
}

func (o VerifySecondaryEmail200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifySecondaryEmail200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableVerifySecondaryEmail200Response struct {
	value *VerifySecondaryEmail200Response
	isSet bool
}

func (v NullableVerifySecondaryEmail200Response) Get() *VerifySecondaryEmail200Response {
	return v.value
}

func (v *NullableVerifySecondaryEmail200Response) Set(val *VerifySecondaryEmail200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifySecondaryEmail200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifySecondaryEmail200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifySecondaryEmail200Response(val *VerifySecondaryEmail200Response) *NullableVerifySecondaryEmail200Response {
	return &NullableVerifySecondaryEmail200Response{value: val, isSet: true}
}

func (v NullableVerifySecondaryEmail200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifySecondaryEmail200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


