/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the SearchDataCustodians200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchDataCustodians200ResponseDataInner{}

// SearchDataCustodians200ResponseDataInner struct for SearchDataCustodians200ResponseDataInner
type SearchDataCustodians200ResponseDataInner struct {
	Source []SearchDataCustodians200ResponseDataInnerSourceInner `json:"_source,omitempty"`
	Highlight []SearchDataUses200ResponseDataInnerHighlightInner `json:"highlight,omitempty"`
}

// NewSearchDataCustodians200ResponseDataInner instantiates a new SearchDataCustodians200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchDataCustodians200ResponseDataInner() *SearchDataCustodians200ResponseDataInner {
	this := SearchDataCustodians200ResponseDataInner{}
	return &this
}

// NewSearchDataCustodians200ResponseDataInnerWithDefaults instantiates a new SearchDataCustodians200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchDataCustodians200ResponseDataInnerWithDefaults() *SearchDataCustodians200ResponseDataInner {
	this := SearchDataCustodians200ResponseDataInner{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SearchDataCustodians200ResponseDataInner) GetSource() []SearchDataCustodians200ResponseDataInnerSourceInner {
	if o == nil || IsNil(o.Source) {
		var ret []SearchDataCustodians200ResponseDataInnerSourceInner
		return ret
	}
	return o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataCustodians200ResponseDataInner) GetSourceOk() ([]SearchDataCustodians200ResponseDataInnerSourceInner, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SearchDataCustodians200ResponseDataInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given []SearchDataCustodians200ResponseDataInnerSourceInner and assigns it to the Source field.
func (o *SearchDataCustodians200ResponseDataInner) SetSource(v []SearchDataCustodians200ResponseDataInnerSourceInner) {
	o.Source = v
}

// GetHighlight returns the Highlight field value if set, zero value otherwise.
func (o *SearchDataCustodians200ResponseDataInner) GetHighlight() []SearchDataUses200ResponseDataInnerHighlightInner {
	if o == nil || IsNil(o.Highlight) {
		var ret []SearchDataUses200ResponseDataInnerHighlightInner
		return ret
	}
	return o.Highlight
}

// GetHighlightOk returns a tuple with the Highlight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataCustodians200ResponseDataInner) GetHighlightOk() ([]SearchDataUses200ResponseDataInnerHighlightInner, bool) {
	if o == nil || IsNil(o.Highlight) {
		return nil, false
	}
	return o.Highlight, true
}

// HasHighlight returns a boolean if a field has been set.
func (o *SearchDataCustodians200ResponseDataInner) HasHighlight() bool {
	if o != nil && !IsNil(o.Highlight) {
		return true
	}

	return false
}

// SetHighlight gets a reference to the given []SearchDataUses200ResponseDataInnerHighlightInner and assigns it to the Highlight field.
func (o *SearchDataCustodians200ResponseDataInner) SetHighlight(v []SearchDataUses200ResponseDataInnerHighlightInner) {
	o.Highlight = v
}

func (o SearchDataCustodians200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchDataCustodians200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["_source"] = o.Source
	}
	if !IsNil(o.Highlight) {
		toSerialize["highlight"] = o.Highlight
	}
	return toSerialize, nil
}

type NullableSearchDataCustodians200ResponseDataInner struct {
	value *SearchDataCustodians200ResponseDataInner
	isSet bool
}

func (v NullableSearchDataCustodians200ResponseDataInner) Get() *SearchDataCustodians200ResponseDataInner {
	return v.value
}

func (v *NullableSearchDataCustodians200ResponseDataInner) Set(val *SearchDataCustodians200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchDataCustodians200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchDataCustodians200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchDataCustodians200ResponseDataInner(val *SearchDataCustodians200ResponseDataInner) *NullableSearchDataCustodians200ResponseDataInner {
	return &NullableSearchDataCustodians200ResponseDataInner{value: val, isSet: true}
}

func (v NullableSearchDataCustodians200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchDataCustodians200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


