/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the SearchDataCustodians200ResponseDataInnerSourceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchDataCustodians200ResponseDataInnerSourceInner{}

// SearchDataCustodians200ResponseDataInnerSourceInner struct for SearchDataCustodians200ResponseDataInnerSourceInner
type SearchDataCustodians200ResponseDataInnerSourceInner struct {
	Name *string `json:"name,omitempty"`
	TeamLogo *string `json:"team_logo,omitempty"`
}

// NewSearchDataCustodians200ResponseDataInnerSourceInner instantiates a new SearchDataCustodians200ResponseDataInnerSourceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchDataCustodians200ResponseDataInnerSourceInner() *SearchDataCustodians200ResponseDataInnerSourceInner {
	this := SearchDataCustodians200ResponseDataInnerSourceInner{}
	return &this
}

// NewSearchDataCustodians200ResponseDataInnerSourceInnerWithDefaults instantiates a new SearchDataCustodians200ResponseDataInnerSourceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchDataCustodians200ResponseDataInnerSourceInnerWithDefaults() *SearchDataCustodians200ResponseDataInnerSourceInner {
	this := SearchDataCustodians200ResponseDataInnerSourceInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) SetName(v string) {
	o.Name = &v
}

// GetTeamLogo returns the TeamLogo field value if set, zero value otherwise.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) GetTeamLogo() string {
	if o == nil || IsNil(o.TeamLogo) {
		var ret string
		return ret
	}
	return *o.TeamLogo
}

// GetTeamLogoOk returns a tuple with the TeamLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) GetTeamLogoOk() (*string, bool) {
	if o == nil || IsNil(o.TeamLogo) {
		return nil, false
	}
	return o.TeamLogo, true
}

// HasTeamLogo returns a boolean if a field has been set.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) HasTeamLogo() bool {
	if o != nil && !IsNil(o.TeamLogo) {
		return true
	}

	return false
}

// SetTeamLogo gets a reference to the given string and assigns it to the TeamLogo field.
func (o *SearchDataCustodians200ResponseDataInnerSourceInner) SetTeamLogo(v string) {
	o.TeamLogo = &v
}

func (o SearchDataCustodians200ResponseDataInnerSourceInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchDataCustodians200ResponseDataInnerSourceInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TeamLogo) {
		toSerialize["team_logo"] = o.TeamLogo
	}
	return toSerialize, nil
}

type NullableSearchDataCustodians200ResponseDataInnerSourceInner struct {
	value *SearchDataCustodians200ResponseDataInnerSourceInner
	isSet bool
}

func (v NullableSearchDataCustodians200ResponseDataInnerSourceInner) Get() *SearchDataCustodians200ResponseDataInnerSourceInner {
	return v.value
}

func (v *NullableSearchDataCustodians200ResponseDataInnerSourceInner) Set(val *SearchDataCustodians200ResponseDataInnerSourceInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchDataCustodians200ResponseDataInnerSourceInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchDataCustodians200ResponseDataInnerSourceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchDataCustodians200ResponseDataInnerSourceInner(val *SearchDataCustodians200ResponseDataInnerSourceInner) *NullableSearchDataCustodians200ResponseDataInnerSourceInner {
	return &NullableSearchDataCustodians200ResponseDataInnerSourceInner{value: val, isSet: true}
}

func (v NullableSearchDataCustodians200ResponseDataInnerSourceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchDataCustodians200ResponseDataInnerSourceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


