/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the RetrieveWidgetData403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetrieveWidgetData403Response{}

// RetrieveWidgetData403Response struct for RetrieveWidgetData403Response
type RetrieveWidgetData403Response struct {
	Message *string `json:"message,omitempty"`
}

// NewRetrieveWidgetData403Response instantiates a new RetrieveWidgetData403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetrieveWidgetData403Response() *RetrieveWidgetData403Response {
	this := RetrieveWidgetData403Response{}
	return &this
}

// NewRetrieveWidgetData403ResponseWithDefaults instantiates a new RetrieveWidgetData403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetrieveWidgetData403ResponseWithDefaults() *RetrieveWidgetData403Response {
	this := RetrieveWidgetData403Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RetrieveWidgetData403Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrieveWidgetData403Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RetrieveWidgetData403Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RetrieveWidgetData403Response) SetMessage(v string) {
	o.Message = &v
}

func (o RetrieveWidgetData403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetrieveWidgetData403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableRetrieveWidgetData403Response struct {
	value *RetrieveWidgetData403Response
	isSet bool
}

func (v NullableRetrieveWidgetData403Response) Get() *RetrieveWidgetData403Response {
	return v.value
}

func (v *NullableRetrieveWidgetData403Response) Set(val *RetrieveWidgetData403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRetrieveWidgetData403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRetrieveWidgetData403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetrieveWidgetData403Response(val *RetrieveWidgetData403Response) *NullableRetrieveWidgetData403Response {
	return &NullableRetrieveWidgetData403Response{value: val, isSet: true}
}

func (v NullableRetrieveWidgetData403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetrieveWidgetData403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


