/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the SearchToolsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchToolsRequest{}

// SearchToolsRequest struct for SearchToolsRequest
type SearchToolsRequest struct {
	Query *string `json:"query,omitempty"`
}

// NewSearchToolsRequest instantiates a new SearchToolsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchToolsRequest() *SearchToolsRequest {
	this := SearchToolsRequest{}
	return &this
}

// NewSearchToolsRequestWithDefaults instantiates a new SearchToolsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchToolsRequestWithDefaults() *SearchToolsRequest {
	this := SearchToolsRequest{}
	return &this
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *SearchToolsRequest) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchToolsRequest) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *SearchToolsRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *SearchToolsRequest) SetQuery(v string) {
	o.Query = &v
}

func (o SearchToolsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchToolsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableSearchToolsRequest struct {
	value *SearchToolsRequest
	isSet bool
}

func (v NullableSearchToolsRequest) Get() *SearchToolsRequest {
	return v.value
}

func (v *NullableSearchToolsRequest) Set(val *SearchToolsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchToolsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchToolsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchToolsRequest(val *SearchToolsRequest) *NullableSearchToolsRequest {
	return &NullableSearchToolsRequest{value: val, isSet: true}
}

func (v NullableSearchToolsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchToolsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


