/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the EditProgrammingLanguagesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditProgrammingLanguagesRequest{}

// EditProgrammingLanguagesRequest struct for EditProgrammingLanguagesRequest
type EditProgrammingLanguagesRequest struct {
	Name *string `json:"name,omitempty"`
	Enabled *string `json:"enabled,omitempty"`
}

// NewEditProgrammingLanguagesRequest instantiates a new EditProgrammingLanguagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditProgrammingLanguagesRequest() *EditProgrammingLanguagesRequest {
	this := EditProgrammingLanguagesRequest{}
	return &this
}

// NewEditProgrammingLanguagesRequestWithDefaults instantiates a new EditProgrammingLanguagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditProgrammingLanguagesRequestWithDefaults() *EditProgrammingLanguagesRequest {
	this := EditProgrammingLanguagesRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EditProgrammingLanguagesRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProgrammingLanguagesRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EditProgrammingLanguagesRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EditProgrammingLanguagesRequest) SetName(v string) {
	o.Name = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *EditProgrammingLanguagesRequest) GetEnabled() string {
	if o == nil || IsNil(o.Enabled) {
		var ret string
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProgrammingLanguagesRequest) GetEnabledOk() (*string, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *EditProgrammingLanguagesRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given string and assigns it to the Enabled field.
func (o *EditProgrammingLanguagesRequest) SetEnabled(v string) {
	o.Enabled = &v
}

func (o EditProgrammingLanguagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditProgrammingLanguagesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableEditProgrammingLanguagesRequest struct {
	value *EditProgrammingLanguagesRequest
	isSet bool
}

func (v NullableEditProgrammingLanguagesRequest) Get() *EditProgrammingLanguagesRequest {
	return v.value
}

func (v *NullableEditProgrammingLanguagesRequest) Set(val *EditProgrammingLanguagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditProgrammingLanguagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditProgrammingLanguagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditProgrammingLanguagesRequest(val *EditProgrammingLanguagesRequest) *NullableEditProgrammingLanguagesRequest {
	return &NullableEditProgrammingLanguagesRequest{value: val, isSet: true}
}

func (v NullableEditProgrammingLanguagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditProgrammingLanguagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


