/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the CreateToolsIntegrations400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateToolsIntegrations400Response{}

// CreateToolsIntegrations400Response struct for CreateToolsIntegrations400Response
type CreateToolsIntegrations400Response struct {
	Message *string `json:"message,omitempty"`
}

// NewCreateToolsIntegrations400Response instantiates a new CreateToolsIntegrations400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateToolsIntegrations400Response() *CreateToolsIntegrations400Response {
	this := CreateToolsIntegrations400Response{}
	return &this
}

// NewCreateToolsIntegrations400ResponseWithDefaults instantiates a new CreateToolsIntegrations400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateToolsIntegrations400ResponseWithDefaults() *CreateToolsIntegrations400Response {
	this := CreateToolsIntegrations400Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateToolsIntegrations400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateToolsIntegrations400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateToolsIntegrations400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateToolsIntegrations400Response) SetMessage(v string) {
	o.Message = &v
}

func (o CreateToolsIntegrations400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateToolsIntegrations400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateToolsIntegrations400Response struct {
	value *CreateToolsIntegrations400Response
	isSet bool
}

func (v NullableCreateToolsIntegrations400Response) Get() *CreateToolsIntegrations400Response {
	return v.value
}

func (v *NullableCreateToolsIntegrations400Response) Set(val *CreateToolsIntegrations400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateToolsIntegrations400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateToolsIntegrations400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateToolsIntegrations400Response(val *CreateToolsIntegrations400Response) *NullableCreateToolsIntegrations400Response {
	return &NullableCreateToolsIntegrations400Response{value: val, isSet: true}
}

func (v NullableCreateToolsIntegrations400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateToolsIntegrations400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


