/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchAllDarIntegrations200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllDarIntegrations200Response{}

// FetchAllDarIntegrations200Response struct for FetchAllDarIntegrations200Response
type FetchAllDarIntegrations200Response struct {
	Message *string `json:"message,omitempty"`
	Data []FetchAllDarIntegrations200ResponseDataInner `json:"data,omitempty"`
}

// NewFetchAllDarIntegrations200Response instantiates a new FetchAllDarIntegrations200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllDarIntegrations200Response() *FetchAllDarIntegrations200Response {
	this := FetchAllDarIntegrations200Response{}
	return &this
}

// NewFetchAllDarIntegrations200ResponseWithDefaults instantiates a new FetchAllDarIntegrations200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllDarIntegrations200ResponseWithDefaults() *FetchAllDarIntegrations200Response {
	this := FetchAllDarIntegrations200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchAllDarIntegrations200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllDarIntegrations200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchAllDarIntegrations200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchAllDarIntegrations200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchAllDarIntegrations200Response) GetData() []FetchAllDarIntegrations200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []FetchAllDarIntegrations200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllDarIntegrations200Response) GetDataOk() ([]FetchAllDarIntegrations200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchAllDarIntegrations200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []FetchAllDarIntegrations200ResponseDataInner and assigns it to the Data field.
func (o *FetchAllDarIntegrations200Response) SetData(v []FetchAllDarIntegrations200ResponseDataInner) {
	o.Data = v
}

func (o FetchAllDarIntegrations200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllDarIntegrations200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchAllDarIntegrations200Response struct {
	value *FetchAllDarIntegrations200Response
	isSet bool
}

func (v NullableFetchAllDarIntegrations200Response) Get() *FetchAllDarIntegrations200Response {
	return v.value
}

func (v *NullableFetchAllDarIntegrations200Response) Set(val *FetchAllDarIntegrations200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllDarIntegrations200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllDarIntegrations200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllDarIntegrations200Response(val *FetchAllDarIntegrations200Response) *NullableFetchAllDarIntegrations200Response {
	return &NullableFetchAllDarIntegrations200Response{value: val, isSet: true}
}

func (v NullableFetchAllDarIntegrations200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllDarIntegrations200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


