/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAliasesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAliasesRequest{}

// CreateAliasesRequest struct for CreateAliasesRequest
type CreateAliasesRequest struct {
	Name string `json:"name"`
}

type _CreateAliasesRequest CreateAliasesRequest

// NewCreateAliasesRequest instantiates a new CreateAliasesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAliasesRequest(name string) *CreateAliasesRequest {
	this := CreateAliasesRequest{}
	this.Name = name
	return &this
}

// NewCreateAliasesRequestWithDefaults instantiates a new CreateAliasesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAliasesRequestWithDefaults() *CreateAliasesRequest {
	this := CreateAliasesRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAliasesRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAliasesRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAliasesRequest) SetName(v string) {
	o.Name = v
}

func (o CreateAliasesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAliasesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateAliasesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAliasesRequest := _CreateAliasesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAliasesRequest)

	if err != nil {
		return err
	}

	*o = CreateAliasesRequest(varCreateAliasesRequest)

	return err
}

type NullableCreateAliasesRequest struct {
	value *CreateAliasesRequest
	isSet bool
}

func (v NullableCreateAliasesRequest) Get() *CreateAliasesRequest {
	return v.value
}

func (v *NullableCreateAliasesRequest) Set(val *CreateAliasesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAliasesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAliasesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAliasesRequest(val *CreateAliasesRequest) *NullableCreateAliasesRequest {
	return &NullableCreateAliasesRequest{value: val, isSet: true}
}

func (v NullableCreateAliasesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAliasesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


