/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the CreateToolsRequestCollectionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateToolsRequestCollectionsInner{}

// CreateToolsRequestCollectionsInner struct for CreateToolsRequestCollectionsInner
type CreateToolsRequestCollectionsInner struct {
	Id *int32 `json:"id,omitempty"`
	UserId *int32 `json:"user_id,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewCreateToolsRequestCollectionsInner instantiates a new CreateToolsRequestCollectionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateToolsRequestCollectionsInner() *CreateToolsRequestCollectionsInner {
	this := CreateToolsRequestCollectionsInner{}
	return &this
}

// NewCreateToolsRequestCollectionsInnerWithDefaults instantiates a new CreateToolsRequestCollectionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateToolsRequestCollectionsInnerWithDefaults() *CreateToolsRequestCollectionsInner {
	this := CreateToolsRequestCollectionsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateToolsRequestCollectionsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateToolsRequestCollectionsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateToolsRequestCollectionsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CreateToolsRequestCollectionsInner) SetId(v int32) {
	o.Id = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CreateToolsRequestCollectionsInner) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateToolsRequestCollectionsInner) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CreateToolsRequestCollectionsInner) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *CreateToolsRequestCollectionsInner) SetUserId(v int32) {
	o.UserId = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CreateToolsRequestCollectionsInner) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateToolsRequestCollectionsInner) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CreateToolsRequestCollectionsInner) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *CreateToolsRequestCollectionsInner) SetReason(v string) {
	o.Reason = &v
}

func (o CreateToolsRequestCollectionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateToolsRequestCollectionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableCreateToolsRequestCollectionsInner struct {
	value *CreateToolsRequestCollectionsInner
	isSet bool
}

func (v NullableCreateToolsRequestCollectionsInner) Get() *CreateToolsRequestCollectionsInner {
	return v.value
}

func (v *NullableCreateToolsRequestCollectionsInner) Set(val *CreateToolsRequestCollectionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateToolsRequestCollectionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateToolsRequestCollectionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateToolsRequestCollectionsInner(val *CreateToolsRequestCollectionsInner) *NullableCreateToolsRequestCollectionsInner {
	return &NullableCreateToolsRequestCollectionsInner{value: val, isSet: true}
}

func (v NullableCreateToolsRequestCollectionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateToolsRequestCollectionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


