/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the CreateCsat422Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCsat422Response{}

// CreateCsat422Response struct for CreateCsat422Response
type CreateCsat422Response struct {
	Message *string `json:"message,omitempty"`
	Id *int32 `json:"id,omitempty"`
	Errors map[string]interface{} `json:"errors,omitempty"`
}

// NewCreateCsat422Response instantiates a new CreateCsat422Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCsat422Response() *CreateCsat422Response {
	this := CreateCsat422Response{}
	return &this
}

// NewCreateCsat422ResponseWithDefaults instantiates a new CreateCsat422Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCsat422ResponseWithDefaults() *CreateCsat422Response {
	this := CreateCsat422Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateCsat422Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCsat422Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateCsat422Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateCsat422Response) SetMessage(v string) {
	o.Message = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateCsat422Response) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCsat422Response) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateCsat422Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CreateCsat422Response) SetId(v int32) {
	o.Id = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateCsat422Response) GetErrors() map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCsat422Response) GetErrorsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return map[string]interface{}{}, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateCsat422Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given map[string]interface{} and assigns it to the Errors field.
func (o *CreateCsat422Response) SetErrors(v map[string]interface{}) {
	o.Errors = v
}

func (o CreateCsat422Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCsat422Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableCreateCsat422Response struct {
	value *CreateCsat422Response
	isSet bool
}

func (v NullableCreateCsat422Response) Get() *CreateCsat422Response {
	return v.value
}

func (v *NullableCreateCsat422Response) Set(val *CreateCsat422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCsat422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCsat422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCsat422Response(val *CreateCsat422Response) *NullableCreateCsat422Response {
	return &NullableCreateCsat422Response{value: val, isSet: true}
}

func (v NullableCreateCsat422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCsat422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


