/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchDashboardDownloadCsvV3500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchDashboardDownloadCsvV3500Response{}

// FetchDashboardDownloadCsvV3500Response struct for FetchDashboardDownloadCsvV3500Response
type FetchDashboardDownloadCsvV3500Response struct {
	Message *string `json:"message,omitempty"`
	Data *string `json:"data,omitempty"`
}

// NewFetchDashboardDownloadCsvV3500Response instantiates a new FetchDashboardDownloadCsvV3500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchDashboardDownloadCsvV3500Response() *FetchDashboardDownloadCsvV3500Response {
	this := FetchDashboardDownloadCsvV3500Response{}
	return &this
}

// NewFetchDashboardDownloadCsvV3500ResponseWithDefaults instantiates a new FetchDashboardDownloadCsvV3500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchDashboardDownloadCsvV3500ResponseWithDefaults() *FetchDashboardDownloadCsvV3500Response {
	this := FetchDashboardDownloadCsvV3500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchDashboardDownloadCsvV3500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchDashboardDownloadCsvV3500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchDashboardDownloadCsvV3500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchDashboardDownloadCsvV3500Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchDashboardDownloadCsvV3500Response) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchDashboardDownloadCsvV3500Response) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchDashboardDownloadCsvV3500Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *FetchDashboardDownloadCsvV3500Response) SetData(v string) {
	o.Data = &v
}

func (o FetchDashboardDownloadCsvV3500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchDashboardDownloadCsvV3500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchDashboardDownloadCsvV3500Response struct {
	value *FetchDashboardDownloadCsvV3500Response
	isSet bool
}

func (v NullableFetchDashboardDownloadCsvV3500Response) Get() *FetchDashboardDownloadCsvV3500Response {
	return v.value
}

func (v *NullableFetchDashboardDownloadCsvV3500Response) Set(val *FetchDashboardDownloadCsvV3500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchDashboardDownloadCsvV3500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchDashboardDownloadCsvV3500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchDashboardDownloadCsvV3500Response(val *FetchDashboardDownloadCsvV3500Response) *NullableFetchDashboardDownloadCsvV3500Response {
	return &NullableFetchDashboardDownloadCsvV3500Response{value: val, isSet: true}
}

func (v NullableFetchDashboardDownloadCsvV3500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchDashboardDownloadCsvV3500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


