/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the EditUsers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditUsers200Response{}

// EditUsers200Response struct for EditUsers200Response
type EditUsers200Response struct {
	Message *string `json:"message,omitempty"`
	Data *User `json:"data,omitempty"`
}

// NewEditUsers200Response instantiates a new EditUsers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditUsers200Response() *EditUsers200Response {
	this := EditUsers200Response{}
	return &this
}

// NewEditUsers200ResponseWithDefaults instantiates a new EditUsers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditUsers200ResponseWithDefaults() *EditUsers200Response {
	this := EditUsers200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *EditUsers200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditUsers200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *EditUsers200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *EditUsers200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EditUsers200Response) GetData() User {
	if o == nil || IsNil(o.Data) {
		var ret User
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditUsers200Response) GetDataOk() (*User, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EditUsers200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given User and assigns it to the Data field.
func (o *EditUsers200Response) SetData(v User) {
	o.Data = &v
}

func (o EditUsers200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditUsers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEditUsers200Response struct {
	value *EditUsers200Response
	isSet bool
}

func (v NullableEditUsers200Response) Get() *EditUsers200Response {
	return v.value
}

func (v *NullableEditUsers200Response) Set(val *EditUsers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEditUsers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEditUsers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditUsers200Response(val *EditUsers200Response) *NullableEditUsers200Response {
	return &NullableEditUsers200Response{value: val, isSet: true}
}

func (v NullableEditUsers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditUsers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


