/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchQuestionBankQuestionVersion200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchQuestionBankQuestionVersion200Response{}

// FetchQuestionBankQuestionVersion200Response struct for FetchQuestionBankQuestionVersion200Response
type FetchQuestionBankQuestionVersion200Response struct {
	Message *string `json:"message,omitempty"`
	Data *FetchQuestionBankQuestionVersion200ResponseData `json:"data,omitempty"`
}

// NewFetchQuestionBankQuestionVersion200Response instantiates a new FetchQuestionBankQuestionVersion200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchQuestionBankQuestionVersion200Response() *FetchQuestionBankQuestionVersion200Response {
	this := FetchQuestionBankQuestionVersion200Response{}
	return &this
}

// NewFetchQuestionBankQuestionVersion200ResponseWithDefaults instantiates a new FetchQuestionBankQuestionVersion200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchQuestionBankQuestionVersion200ResponseWithDefaults() *FetchQuestionBankQuestionVersion200Response {
	this := FetchQuestionBankQuestionVersion200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchQuestionBankQuestionVersion200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchQuestionBankQuestionVersion200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchQuestionBankQuestionVersion200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchQuestionBankQuestionVersion200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchQuestionBankQuestionVersion200Response) GetData() FetchQuestionBankQuestionVersion200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret FetchQuestionBankQuestionVersion200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchQuestionBankQuestionVersion200Response) GetDataOk() (*FetchQuestionBankQuestionVersion200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchQuestionBankQuestionVersion200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FetchQuestionBankQuestionVersion200ResponseData and assigns it to the Data field.
func (o *FetchQuestionBankQuestionVersion200Response) SetData(v FetchQuestionBankQuestionVersion200ResponseData) {
	o.Data = &v
}

func (o FetchQuestionBankQuestionVersion200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchQuestionBankQuestionVersion200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchQuestionBankQuestionVersion200Response struct {
	value *FetchQuestionBankQuestionVersion200Response
	isSet bool
}

func (v NullableFetchQuestionBankQuestionVersion200Response) Get() *FetchQuestionBankQuestionVersion200Response {
	return v.value
}

func (v *NullableFetchQuestionBankQuestionVersion200Response) Set(val *FetchQuestionBankQuestionVersion200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchQuestionBankQuestionVersion200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchQuestionBankQuestionVersion200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchQuestionBankQuestionVersion200Response(val *FetchQuestionBankQuestionVersion200Response) *NullableFetchQuestionBankQuestionVersion200Response {
	return &NullableFetchQuestionBankQuestionVersion200Response{value: val, isSet: true}
}

func (v NullableFetchQuestionBankQuestionVersion200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchQuestionBankQuestionVersion200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


