/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchWidget200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchWidget200Response{}

// FetchWidget200Response struct for FetchWidget200Response
type FetchWidget200Response struct {
	Data *Widget `json:"data,omitempty"`
}

// NewFetchWidget200Response instantiates a new FetchWidget200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchWidget200Response() *FetchWidget200Response {
	this := FetchWidget200Response{}
	return &this
}

// NewFetchWidget200ResponseWithDefaults instantiates a new FetchWidget200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchWidget200ResponseWithDefaults() *FetchWidget200Response {
	this := FetchWidget200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchWidget200Response) GetData() Widget {
	if o == nil || IsNil(o.Data) {
		var ret Widget
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchWidget200Response) GetDataOk() (*Widget, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchWidget200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Widget and assigns it to the Data field.
func (o *FetchWidget200Response) SetData(v Widget) {
	o.Data = &v
}

func (o FetchWidget200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchWidget200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchWidget200Response struct {
	value *FetchWidget200Response
	isSet bool
}

func (v NullableFetchWidget200Response) Get() *FetchWidget200Response {
	return v.value
}

func (v *NullableFetchWidget200Response) Set(val *FetchWidget200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchWidget200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchWidget200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchWidget200Response(val *FetchWidget200Response) *NullableFetchWidget200Response {
	return &NullableFetchWidget200Response{value: val, isSet: true}
}

func (v NullableFetchWidget200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchWidget200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


