/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchAllSavedSearches200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllSavedSearches200Response{}

// FetchAllSavedSearches200Response struct for FetchAllSavedSearches200Response
type FetchAllSavedSearches200Response struct {
	Message *string `json:"message,omitempty"`
	Data []SavedSearch `json:"data,omitempty"`
}

// NewFetchAllSavedSearches200Response instantiates a new FetchAllSavedSearches200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllSavedSearches200Response() *FetchAllSavedSearches200Response {
	this := FetchAllSavedSearches200Response{}
	return &this
}

// NewFetchAllSavedSearches200ResponseWithDefaults instantiates a new FetchAllSavedSearches200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllSavedSearches200ResponseWithDefaults() *FetchAllSavedSearches200Response {
	this := FetchAllSavedSearches200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchAllSavedSearches200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllSavedSearches200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchAllSavedSearches200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchAllSavedSearches200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchAllSavedSearches200Response) GetData() []SavedSearch {
	if o == nil || IsNil(o.Data) {
		var ret []SavedSearch
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllSavedSearches200Response) GetDataOk() ([]SavedSearch, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchAllSavedSearches200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SavedSearch and assigns it to the Data field.
func (o *FetchAllSavedSearches200Response) SetData(v []SavedSearch) {
	o.Data = v
}

func (o FetchAllSavedSearches200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllSavedSearches200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchAllSavedSearches200Response struct {
	value *FetchAllSavedSearches200Response
	isSet bool
}

func (v NullableFetchAllSavedSearches200Response) Get() *FetchAllSavedSearches200Response {
	return v.value
}

func (v *NullableFetchAllSavedSearches200Response) Set(val *FetchAllSavedSearches200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllSavedSearches200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllSavedSearches200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllSavedSearches200Response(val *FetchAllSavedSearches200Response) *NullableFetchAllSavedSearches200Response {
	return &NullableFetchAllSavedSearches200Response{value: val, isSet: true}
}

func (v NullableFetchAllSavedSearches200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllSavedSearches200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


