/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the EditCsat200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditCsat200Response{}

// EditCsat200Response struct for EditCsat200Response
type EditCsat200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewEditCsat200Response instantiates a new EditCsat200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditCsat200Response() *EditCsat200Response {
	this := EditCsat200Response{}
	return &this
}

// NewEditCsat200ResponseWithDefaults instantiates a new EditCsat200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditCsat200ResponseWithDefaults() *EditCsat200Response {
	this := EditCsat200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *EditCsat200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditCsat200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *EditCsat200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *EditCsat200Response) SetMessage(v string) {
	o.Message = &v
}

func (o EditCsat200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditCsat200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableEditCsat200Response struct {
	value *EditCsat200Response
	isSet bool
}

func (v NullableEditCsat200Response) Get() *EditCsat200Response {
	return v.value
}

func (v *NullableEditCsat200Response) Set(val *EditCsat200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEditCsat200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEditCsat200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditCsat200Response(val *EditCsat200Response) *NullableEditCsat200Response {
	return &NullableEditCsat200Response{value: val, isSet: true}
}

func (v NullableEditCsat200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditCsat200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


