/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"time"
)

// checks if the FetchAllReviews200ResponseDataInnerTool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllReviews200ResponseDataInnerTool{}

// FetchAllReviews200ResponseDataInnerTool struct for FetchAllReviews200ResponseDataInnerTool
type FetchAllReviews200ResponseDataInnerTool struct {
	Id *int32 `json:"id,omitempty"`
	MongoObjectId *string `json:"mongo_object_id,omitempty"`
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	Description *string `json:"description,omitempty"`
	License *string `json:"license,omitempty"`
	TechStack *string `json:"tech_stack,omitempty"`
	UserId *int32 `json:"user_id,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewFetchAllReviews200ResponseDataInnerTool instantiates a new FetchAllReviews200ResponseDataInnerTool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllReviews200ResponseDataInnerTool() *FetchAllReviews200ResponseDataInnerTool {
	this := FetchAllReviews200ResponseDataInnerTool{}
	return &this
}

// NewFetchAllReviews200ResponseDataInnerToolWithDefaults instantiates a new FetchAllReviews200ResponseDataInnerTool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllReviews200ResponseDataInnerToolWithDefaults() *FetchAllReviews200ResponseDataInnerTool {
	this := FetchAllReviews200ResponseDataInnerTool{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetId(v int32) {
	o.Id = &v
}

// GetMongoObjectId returns the MongoObjectId field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetMongoObjectId() string {
	if o == nil || IsNil(o.MongoObjectId) {
		var ret string
		return ret
	}
	return *o.MongoObjectId
}

// GetMongoObjectIdOk returns a tuple with the MongoObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetMongoObjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.MongoObjectId) {
		return nil, false
	}
	return o.MongoObjectId, true
}

// HasMongoObjectId returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasMongoObjectId() bool {
	if o != nil && !IsNil(o.MongoObjectId) {
		return true
	}

	return false
}

// SetMongoObjectId gets a reference to the given string and assigns it to the MongoObjectId field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetMongoObjectId(v string) {
	o.MongoObjectId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetUrl(v string) {
	o.Url = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetDescription(v string) {
	o.Description = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetLicense() string {
	if o == nil || IsNil(o.License) {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetLicenseOk() (*string, bool) {
	if o == nil || IsNil(o.License) {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasLicense() bool {
	if o != nil && !IsNil(o.License) {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetLicense(v string) {
	o.License = &v
}

// GetTechStack returns the TechStack field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetTechStack() string {
	if o == nil || IsNil(o.TechStack) {
		var ret string
		return ret
	}
	return *o.TechStack
}

// GetTechStackOk returns a tuple with the TechStack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetTechStackOk() (*string, bool) {
	if o == nil || IsNil(o.TechStack) {
		return nil, false
	}
	return o.TechStack, true
}

// HasTechStack returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasTechStack() bool {
	if o != nil && !IsNil(o.TechStack) {
		return true
	}

	return false
}

// SetTechStack gets a reference to the given string and assigns it to the TechStack field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetTechStack(v string) {
	o.TechStack = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetUserId(v int32) {
	o.UserId = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *FetchAllReviews200ResponseDataInnerTool) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *FetchAllReviews200ResponseDataInnerTool) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *FetchAllReviews200ResponseDataInnerTool) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

func (o FetchAllReviews200ResponseDataInnerTool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllReviews200ResponseDataInnerTool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MongoObjectId) {
		toSerialize["mongo_object_id"] = o.MongoObjectId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.License) {
		toSerialize["license"] = o.License
	}
	if !IsNil(o.TechStack) {
		toSerialize["tech_stack"] = o.TechStack
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	return toSerialize, nil
}

type NullableFetchAllReviews200ResponseDataInnerTool struct {
	value *FetchAllReviews200ResponseDataInnerTool
	isSet bool
}

func (v NullableFetchAllReviews200ResponseDataInnerTool) Get() *FetchAllReviews200ResponseDataInnerTool {
	return v.value
}

func (v *NullableFetchAllReviews200ResponseDataInnerTool) Set(val *FetchAllReviews200ResponseDataInnerTool) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllReviews200ResponseDataInnerTool) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllReviews200ResponseDataInnerTool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllReviews200ResponseDataInnerTool(val *FetchAllReviews200ResponseDataInnerTool) *NullableFetchAllReviews200ResponseDataInnerTool {
	return &NullableFetchAllReviews200ResponseDataInnerTool{value: val, isSet: true}
}

func (v NullableFetchAllReviews200ResponseDataInnerTool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllReviews200ResponseDataInnerTool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


