/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDarIntegrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDarIntegrationRequest{}

// UpdateDarIntegrationRequest struct for UpdateDarIntegrationRequest
type UpdateDarIntegrationRequest struct {
	Enabled int32 `json:"enabled"`
	NotificationEmail string `json:"notification_email"`
	OutboundAuthType string `json:"outbound_auth_type"`
	OutboundAuthKey string `json:"outbound_auth_key"`
	OutboundEndpointsBaseUrl string `json:"outbound_endpoints_base_url"`
	OutboundEndpointsEnquiry string `json:"outbound_endpoints_enquiry"`
	OutboundEndpoints5safes string `json:"outbound_endpoints_5safes"`
	OutboundEndpoints5safesFiles string `json:"outbound_endpoints_5safes_files"`
	InboundServiceAccountId string `json:"inbound_service_account_id"`
}

type _UpdateDarIntegrationRequest UpdateDarIntegrationRequest

// NewUpdateDarIntegrationRequest instantiates a new UpdateDarIntegrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDarIntegrationRequest(enabled int32, notificationEmail string, outboundAuthType string, outboundAuthKey string, outboundEndpointsBaseUrl string, outboundEndpointsEnquiry string, outboundEndpoints5safes string, outboundEndpoints5safesFiles string, inboundServiceAccountId string) *UpdateDarIntegrationRequest {
	this := UpdateDarIntegrationRequest{}
	this.Enabled = enabled
	this.NotificationEmail = notificationEmail
	this.OutboundAuthType = outboundAuthType
	this.OutboundAuthKey = outboundAuthKey
	this.OutboundEndpointsBaseUrl = outboundEndpointsBaseUrl
	this.OutboundEndpointsEnquiry = outboundEndpointsEnquiry
	this.OutboundEndpoints5safes = outboundEndpoints5safes
	this.OutboundEndpoints5safesFiles = outboundEndpoints5safesFiles
	this.InboundServiceAccountId = inboundServiceAccountId
	return &this
}

// NewUpdateDarIntegrationRequestWithDefaults instantiates a new UpdateDarIntegrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDarIntegrationRequestWithDefaults() *UpdateDarIntegrationRequest {
	this := UpdateDarIntegrationRequest{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *UpdateDarIntegrationRequest) GetEnabled() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetEnabledOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *UpdateDarIntegrationRequest) SetEnabled(v int32) {
	o.Enabled = v
}

// GetNotificationEmail returns the NotificationEmail field value
func (o *UpdateDarIntegrationRequest) GetNotificationEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationEmail
}

// GetNotificationEmailOk returns a tuple with the NotificationEmail field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetNotificationEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationEmail, true
}

// SetNotificationEmail sets field value
func (o *UpdateDarIntegrationRequest) SetNotificationEmail(v string) {
	o.NotificationEmail = v
}

// GetOutboundAuthType returns the OutboundAuthType field value
func (o *UpdateDarIntegrationRequest) GetOutboundAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboundAuthType
}

// GetOutboundAuthTypeOk returns a tuple with the OutboundAuthType field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetOutboundAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboundAuthType, true
}

// SetOutboundAuthType sets field value
func (o *UpdateDarIntegrationRequest) SetOutboundAuthType(v string) {
	o.OutboundAuthType = v
}

// GetOutboundAuthKey returns the OutboundAuthKey field value
func (o *UpdateDarIntegrationRequest) GetOutboundAuthKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboundAuthKey
}

// GetOutboundAuthKeyOk returns a tuple with the OutboundAuthKey field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetOutboundAuthKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboundAuthKey, true
}

// SetOutboundAuthKey sets field value
func (o *UpdateDarIntegrationRequest) SetOutboundAuthKey(v string) {
	o.OutboundAuthKey = v
}

// GetOutboundEndpointsBaseUrl returns the OutboundEndpointsBaseUrl field value
func (o *UpdateDarIntegrationRequest) GetOutboundEndpointsBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboundEndpointsBaseUrl
}

// GetOutboundEndpointsBaseUrlOk returns a tuple with the OutboundEndpointsBaseUrl field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetOutboundEndpointsBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboundEndpointsBaseUrl, true
}

// SetOutboundEndpointsBaseUrl sets field value
func (o *UpdateDarIntegrationRequest) SetOutboundEndpointsBaseUrl(v string) {
	o.OutboundEndpointsBaseUrl = v
}

// GetOutboundEndpointsEnquiry returns the OutboundEndpointsEnquiry field value
func (o *UpdateDarIntegrationRequest) GetOutboundEndpointsEnquiry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboundEndpointsEnquiry
}

// GetOutboundEndpointsEnquiryOk returns a tuple with the OutboundEndpointsEnquiry field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetOutboundEndpointsEnquiryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboundEndpointsEnquiry, true
}

// SetOutboundEndpointsEnquiry sets field value
func (o *UpdateDarIntegrationRequest) SetOutboundEndpointsEnquiry(v string) {
	o.OutboundEndpointsEnquiry = v
}

// GetOutboundEndpoints5safes returns the OutboundEndpoints5safes field value
func (o *UpdateDarIntegrationRequest) GetOutboundEndpoints5safes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboundEndpoints5safes
}

// GetOutboundEndpoints5safesOk returns a tuple with the OutboundEndpoints5safes field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetOutboundEndpoints5safesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboundEndpoints5safes, true
}

// SetOutboundEndpoints5safes sets field value
func (o *UpdateDarIntegrationRequest) SetOutboundEndpoints5safes(v string) {
	o.OutboundEndpoints5safes = v
}

// GetOutboundEndpoints5safesFiles returns the OutboundEndpoints5safesFiles field value
func (o *UpdateDarIntegrationRequest) GetOutboundEndpoints5safesFiles() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboundEndpoints5safesFiles
}

// GetOutboundEndpoints5safesFilesOk returns a tuple with the OutboundEndpoints5safesFiles field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetOutboundEndpoints5safesFilesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboundEndpoints5safesFiles, true
}

// SetOutboundEndpoints5safesFiles sets field value
func (o *UpdateDarIntegrationRequest) SetOutboundEndpoints5safesFiles(v string) {
	o.OutboundEndpoints5safesFiles = v
}

// GetInboundServiceAccountId returns the InboundServiceAccountId field value
func (o *UpdateDarIntegrationRequest) GetInboundServiceAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InboundServiceAccountId
}

// GetInboundServiceAccountIdOk returns a tuple with the InboundServiceAccountId field value
// and a boolean to check if the value has been set.
func (o *UpdateDarIntegrationRequest) GetInboundServiceAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InboundServiceAccountId, true
}

// SetInboundServiceAccountId sets field value
func (o *UpdateDarIntegrationRequest) SetInboundServiceAccountId(v string) {
	o.InboundServiceAccountId = v
}

func (o UpdateDarIntegrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDarIntegrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["notification_email"] = o.NotificationEmail
	toSerialize["outbound_auth_type"] = o.OutboundAuthType
	toSerialize["outbound_auth_key"] = o.OutboundAuthKey
	toSerialize["outbound_endpoints_base_url"] = o.OutboundEndpointsBaseUrl
	toSerialize["outbound_endpoints_enquiry"] = o.OutboundEndpointsEnquiry
	toSerialize["outbound_endpoints_5safes"] = o.OutboundEndpoints5safes
	toSerialize["outbound_endpoints_5safes_files"] = o.OutboundEndpoints5safesFiles
	toSerialize["inbound_service_account_id"] = o.InboundServiceAccountId
	return toSerialize, nil
}

func (o *UpdateDarIntegrationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"notification_email",
		"outbound_auth_type",
		"outbound_auth_key",
		"outbound_endpoints_base_url",
		"outbound_endpoints_enquiry",
		"outbound_endpoints_5safes",
		"outbound_endpoints_5safes_files",
		"inbound_service_account_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDarIntegrationRequest := _UpdateDarIntegrationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDarIntegrationRequest)

	if err != nil {
		return err
	}

	*o = UpdateDarIntegrationRequest(varUpdateDarIntegrationRequest)

	return err
}

type NullableUpdateDarIntegrationRequest struct {
	value *UpdateDarIntegrationRequest
	isSet bool
}

func (v NullableUpdateDarIntegrationRequest) Get() *UpdateDarIntegrationRequest {
	return v.value
}

func (v *NullableUpdateDarIntegrationRequest) Set(val *UpdateDarIntegrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDarIntegrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDarIntegrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDarIntegrationRequest(val *UpdateDarIntegrationRequest) *NullableUpdateDarIntegrationRequest {
	return &NullableUpdateDarIntegrationRequest{value: val, isSet: true}
}

func (v NullableUpdateDarIntegrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDarIntegrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


