/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"time"
)

// checks if the GetFederationByFederationIdAndTeamId200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFederationByFederationIdAndTeamId200ResponseData{}

// GetFederationByFederationIdAndTeamId200ResponseData struct for GetFederationByFederationIdAndTeamId200ResponseData
type GetFederationByFederationIdAndTeamId200ResponseData struct {
	Id *int32 `json:"id,omitempty"`
	FederationType *string `json:"federation_type,omitempty"`
	AuthType *string `json:"auth_type,omitempty"`
	AuthSecretKey *string `json:"auth_secret_key,omitempty"`
	EndpointBaseurl *string `json:"endpoint_baseurl,omitempty"`
	EndpointDatasets *string `json:"endpoint_datasets,omitempty"`
	EndpointDataset *string `json:"endpoint_dataset,omitempty"`
	RunTimeHour *int32 `json:"run_time_hour,omitempty"`
	RunTimeMinute *string `json:"run_time_minute,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	EnabledAt NullableTime `json:"enabled_at,omitempty"`
	Counter *int32 `json:"counter,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	Tested *bool `json:"tested,omitempty"`
	Notifications []interface{} `json:"notifications,omitempty"`
	IsRunning *bool `json:"is_running,omitempty"`
}

// NewGetFederationByFederationIdAndTeamId200ResponseData instantiates a new GetFederationByFederationIdAndTeamId200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFederationByFederationIdAndTeamId200ResponseData() *GetFederationByFederationIdAndTeamId200ResponseData {
	this := GetFederationByFederationIdAndTeamId200ResponseData{}
	return &this
}

// NewGetFederationByFederationIdAndTeamId200ResponseDataWithDefaults instantiates a new GetFederationByFederationIdAndTeamId200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFederationByFederationIdAndTeamId200ResponseDataWithDefaults() *GetFederationByFederationIdAndTeamId200ResponseData {
	this := GetFederationByFederationIdAndTeamId200ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetId(v int32) {
	o.Id = &v
}

// GetFederationType returns the FederationType field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetFederationType() string {
	if o == nil || IsNil(o.FederationType) {
		var ret string
		return ret
	}
	return *o.FederationType
}

// GetFederationTypeOk returns a tuple with the FederationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetFederationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FederationType) {
		return nil, false
	}
	return o.FederationType, true
}

// HasFederationType returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasFederationType() bool {
	if o != nil && !IsNil(o.FederationType) {
		return true
	}

	return false
}

// SetFederationType gets a reference to the given string and assigns it to the FederationType field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetFederationType(v string) {
	o.FederationType = &v
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetAuthType() string {
	if o == nil || IsNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetAuthTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthType) {
		return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasAuthType() bool {
	if o != nil && !IsNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetAuthType(v string) {
	o.AuthType = &v
}

// GetAuthSecretKey returns the AuthSecretKey field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetAuthSecretKey() string {
	if o == nil || IsNil(o.AuthSecretKey) {
		var ret string
		return ret
	}
	return *o.AuthSecretKey
}

// GetAuthSecretKeyOk returns a tuple with the AuthSecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetAuthSecretKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AuthSecretKey) {
		return nil, false
	}
	return o.AuthSecretKey, true
}

// HasAuthSecretKey returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasAuthSecretKey() bool {
	if o != nil && !IsNil(o.AuthSecretKey) {
		return true
	}

	return false
}

// SetAuthSecretKey gets a reference to the given string and assigns it to the AuthSecretKey field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetAuthSecretKey(v string) {
	o.AuthSecretKey = &v
}

// GetEndpointBaseurl returns the EndpointBaseurl field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEndpointBaseurl() string {
	if o == nil || IsNil(o.EndpointBaseurl) {
		var ret string
		return ret
	}
	return *o.EndpointBaseurl
}

// GetEndpointBaseurlOk returns a tuple with the EndpointBaseurl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEndpointBaseurlOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointBaseurl) {
		return nil, false
	}
	return o.EndpointBaseurl, true
}

// HasEndpointBaseurl returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasEndpointBaseurl() bool {
	if o != nil && !IsNil(o.EndpointBaseurl) {
		return true
	}

	return false
}

// SetEndpointBaseurl gets a reference to the given string and assigns it to the EndpointBaseurl field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetEndpointBaseurl(v string) {
	o.EndpointBaseurl = &v
}

// GetEndpointDatasets returns the EndpointDatasets field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEndpointDatasets() string {
	if o == nil || IsNil(o.EndpointDatasets) {
		var ret string
		return ret
	}
	return *o.EndpointDatasets
}

// GetEndpointDatasetsOk returns a tuple with the EndpointDatasets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEndpointDatasetsOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointDatasets) {
		return nil, false
	}
	return o.EndpointDatasets, true
}

// HasEndpointDatasets returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasEndpointDatasets() bool {
	if o != nil && !IsNil(o.EndpointDatasets) {
		return true
	}

	return false
}

// SetEndpointDatasets gets a reference to the given string and assigns it to the EndpointDatasets field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetEndpointDatasets(v string) {
	o.EndpointDatasets = &v
}

// GetEndpointDataset returns the EndpointDataset field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEndpointDataset() string {
	if o == nil || IsNil(o.EndpointDataset) {
		var ret string
		return ret
	}
	return *o.EndpointDataset
}

// GetEndpointDatasetOk returns a tuple with the EndpointDataset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEndpointDatasetOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointDataset) {
		return nil, false
	}
	return o.EndpointDataset, true
}

// HasEndpointDataset returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasEndpointDataset() bool {
	if o != nil && !IsNil(o.EndpointDataset) {
		return true
	}

	return false
}

// SetEndpointDataset gets a reference to the given string and assigns it to the EndpointDataset field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetEndpointDataset(v string) {
	o.EndpointDataset = &v
}

// GetRunTimeHour returns the RunTimeHour field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetRunTimeHour() int32 {
	if o == nil || IsNil(o.RunTimeHour) {
		var ret int32
		return ret
	}
	return *o.RunTimeHour
}

// GetRunTimeHourOk returns a tuple with the RunTimeHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetRunTimeHourOk() (*int32, bool) {
	if o == nil || IsNil(o.RunTimeHour) {
		return nil, false
	}
	return o.RunTimeHour, true
}

// HasRunTimeHour returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasRunTimeHour() bool {
	if o != nil && !IsNil(o.RunTimeHour) {
		return true
	}

	return false
}

// SetRunTimeHour gets a reference to the given int32 and assigns it to the RunTimeHour field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetRunTimeHour(v int32) {
	o.RunTimeHour = &v
}

// GetRunTimeMinute returns the RunTimeMinute field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetRunTimeMinute() string {
	if o == nil || IsNil(o.RunTimeMinute) {
		var ret string
		return ret
	}
	return *o.RunTimeMinute
}

// GetRunTimeMinuteOk returns a tuple with the RunTimeMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetRunTimeMinuteOk() (*string, bool) {
	if o == nil || IsNil(o.RunTimeMinute) {
		return nil, false
	}
	return o.RunTimeMinute, true
}

// HasRunTimeMinute returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasRunTimeMinute() bool {
	if o != nil && !IsNil(o.RunTimeMinute) {
		return true
	}

	return false
}

// SetRunTimeMinute gets a reference to the given string and assigns it to the RunTimeMinute field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetRunTimeMinute(v string) {
	o.RunTimeMinute = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetEnabledAt returns the EnabledAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEnabledAt() time.Time {
	if o == nil || IsNil(o.EnabledAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EnabledAt.Get()
}

// GetEnabledAtOk returns a tuple with the EnabledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetEnabledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledAt.Get(), o.EnabledAt.IsSet()
}

// HasEnabledAt returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasEnabledAt() bool {
	if o != nil && o.EnabledAt.IsSet() {
		return true
	}

	return false
}

// SetEnabledAt gets a reference to the given NullableTime and assigns it to the EnabledAt field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetEnabledAt(v time.Time) {
	o.EnabledAt.Set(&v)
}
// SetEnabledAtNil sets the value for EnabledAt to be an explicit nil
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetEnabledAtNil() {
	o.EnabledAt.Set(nil)
}

// UnsetEnabledAt ensures that no value is present for EnabledAt, not even an explicit nil
func (o *GetFederationByFederationIdAndTeamId200ResponseData) UnsetEnabledAt() {
	o.EnabledAt.Unset()
}

// GetCounter returns the Counter field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetCounter() int32 {
	if o == nil || IsNil(o.Counter) {
		var ret int32
		return ret
	}
	return *o.Counter
}

// GetCounterOk returns a tuple with the Counter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetCounterOk() (*int32, bool) {
	if o == nil || IsNil(o.Counter) {
		return nil, false
	}
	return o.Counter, true
}

// HasCounter returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasCounter() bool {
	if o != nil && !IsNil(o.Counter) {
		return true
	}

	return false
}

// SetCounter gets a reference to the given int32 and assigns it to the Counter field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetCounter(v int32) {
	o.Counter = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetTested returns the Tested field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetTested() bool {
	if o == nil || IsNil(o.Tested) {
		var ret bool
		return ret
	}
	return *o.Tested
}

// GetTestedOk returns a tuple with the Tested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetTestedOk() (*bool, bool) {
	if o == nil || IsNil(o.Tested) {
		return nil, false
	}
	return o.Tested, true
}

// HasTested returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasTested() bool {
	if o != nil && !IsNil(o.Tested) {
		return true
	}

	return false
}

// SetTested gets a reference to the given bool and assigns it to the Tested field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetTested(v bool) {
	o.Tested = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetNotifications() []interface{} {
	if o == nil || IsNil(o.Notifications) {
		var ret []interface{}
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetNotificationsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []interface{} and assigns it to the Notifications field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetNotifications(v []interface{}) {
	o.Notifications = v
}

// GetIsRunning returns the IsRunning field value if set, zero value otherwise.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetIsRunning() bool {
	if o == nil || IsNil(o.IsRunning) {
		var ret bool
		return ret
	}
	return *o.IsRunning
}

// GetIsRunningOk returns a tuple with the IsRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) GetIsRunningOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRunning) {
		return nil, false
	}
	return o.IsRunning, true
}

// HasIsRunning returns a boolean if a field has been set.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) HasIsRunning() bool {
	if o != nil && !IsNil(o.IsRunning) {
		return true
	}

	return false
}

// SetIsRunning gets a reference to the given bool and assigns it to the IsRunning field.
func (o *GetFederationByFederationIdAndTeamId200ResponseData) SetIsRunning(v bool) {
	o.IsRunning = &v
}

func (o GetFederationByFederationIdAndTeamId200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFederationByFederationIdAndTeamId200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.FederationType) {
		toSerialize["federation_type"] = o.FederationType
	}
	if !IsNil(o.AuthType) {
		toSerialize["auth_type"] = o.AuthType
	}
	if !IsNil(o.AuthSecretKey) {
		toSerialize["auth_secret_key"] = o.AuthSecretKey
	}
	if !IsNil(o.EndpointBaseurl) {
		toSerialize["endpoint_baseurl"] = o.EndpointBaseurl
	}
	if !IsNil(o.EndpointDatasets) {
		toSerialize["endpoint_datasets"] = o.EndpointDatasets
	}
	if !IsNil(o.EndpointDataset) {
		toSerialize["endpoint_dataset"] = o.EndpointDataset
	}
	if !IsNil(o.RunTimeHour) {
		toSerialize["run_time_hour"] = o.RunTimeHour
	}
	if !IsNil(o.RunTimeMinute) {
		toSerialize["run_time_minute"] = o.RunTimeMinute
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if o.EnabledAt.IsSet() {
		toSerialize["enabled_at"] = o.EnabledAt.Get()
	}
	if !IsNil(o.Counter) {
		toSerialize["counter"] = o.Counter
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Tested) {
		toSerialize["tested"] = o.Tested
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.IsRunning) {
		toSerialize["is_running"] = o.IsRunning
	}
	return toSerialize, nil
}

type NullableGetFederationByFederationIdAndTeamId200ResponseData struct {
	value *GetFederationByFederationIdAndTeamId200ResponseData
	isSet bool
}

func (v NullableGetFederationByFederationIdAndTeamId200ResponseData) Get() *GetFederationByFederationIdAndTeamId200ResponseData {
	return v.value
}

func (v *NullableGetFederationByFederationIdAndTeamId200ResponseData) Set(val *GetFederationByFederationIdAndTeamId200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFederationByFederationIdAndTeamId200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFederationByFederationIdAndTeamId200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFederationByFederationIdAndTeamId200ResponseData(val *GetFederationByFederationIdAndTeamId200ResponseData) *NullableGetFederationByFederationIdAndTeamId200ResponseData {
	return &NullableGetFederationByFederationIdAndTeamId200ResponseData{value: val, isSet: true}
}

func (v NullableGetFederationByFederationIdAndTeamId200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFederationByFederationIdAndTeamId200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


