/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the CreateTeamCollectionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTeamCollectionsRequest{}

// CreateTeamCollectionsRequest struct for CreateTeamCollectionsRequest
type CreateTeamCollectionsRequest struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ImageLink *string `json:"image_link,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	Datasets []CreateTeamCollectionsRequestDatasetsInner `json:"datasets,omitempty"`
	Tools []CreateTeamCollectionsRequestDatasetsInner `json:"tools,omitempty"`
	Dur []CreateTeamCollectionsRequestDatasetsInner `json:"dur,omitempty"`
	Publications []CreateTeamCollectionsRequestDatasetsInner `json:"publications,omitempty"`
	Public *bool `json:"public,omitempty"`
}

// NewCreateTeamCollectionsRequest instantiates a new CreateTeamCollectionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTeamCollectionsRequest() *CreateTeamCollectionsRequest {
	this := CreateTeamCollectionsRequest{}
	return &this
}

// NewCreateTeamCollectionsRequestWithDefaults instantiates a new CreateTeamCollectionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTeamCollectionsRequestWithDefaults() *CreateTeamCollectionsRequest {
	this := CreateTeamCollectionsRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateTeamCollectionsRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTeamCollectionsRequest) SetDescription(v string) {
	o.Description = &v
}

// GetImageLink returns the ImageLink field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetImageLink() string {
	if o == nil || IsNil(o.ImageLink) {
		var ret string
		return ret
	}
	return *o.ImageLink
}

// GetImageLinkOk returns a tuple with the ImageLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetImageLinkOk() (*string, bool) {
	if o == nil || IsNil(o.ImageLink) {
		return nil, false
	}
	return o.ImageLink, true
}

// HasImageLink returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasImageLink() bool {
	if o != nil && !IsNil(o.ImageLink) {
		return true
	}

	return false
}

// SetImageLink gets a reference to the given string and assigns it to the ImageLink field.
func (o *CreateTeamCollectionsRequest) SetImageLink(v string) {
	o.ImageLink = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateTeamCollectionsRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetKeywords() []string {
	if o == nil || IsNil(o.Keywords) {
		var ret []string
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []string and assigns it to the Keywords field.
func (o *CreateTeamCollectionsRequest) SetKeywords(v []string) {
	o.Keywords = v
}

// GetDatasets returns the Datasets field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetDatasets() []CreateTeamCollectionsRequestDatasetsInner {
	if o == nil || IsNil(o.Datasets) {
		var ret []CreateTeamCollectionsRequestDatasetsInner
		return ret
	}
	return o.Datasets
}

// GetDatasetsOk returns a tuple with the Datasets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetDatasetsOk() ([]CreateTeamCollectionsRequestDatasetsInner, bool) {
	if o == nil || IsNil(o.Datasets) {
		return nil, false
	}
	return o.Datasets, true
}

// HasDatasets returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasDatasets() bool {
	if o != nil && !IsNil(o.Datasets) {
		return true
	}

	return false
}

// SetDatasets gets a reference to the given []CreateTeamCollectionsRequestDatasetsInner and assigns it to the Datasets field.
func (o *CreateTeamCollectionsRequest) SetDatasets(v []CreateTeamCollectionsRequestDatasetsInner) {
	o.Datasets = v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetTools() []CreateTeamCollectionsRequestDatasetsInner {
	if o == nil || IsNil(o.Tools) {
		var ret []CreateTeamCollectionsRequestDatasetsInner
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetToolsOk() ([]CreateTeamCollectionsRequestDatasetsInner, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []CreateTeamCollectionsRequestDatasetsInner and assigns it to the Tools field.
func (o *CreateTeamCollectionsRequest) SetTools(v []CreateTeamCollectionsRequestDatasetsInner) {
	o.Tools = v
}

// GetDur returns the Dur field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetDur() []CreateTeamCollectionsRequestDatasetsInner {
	if o == nil || IsNil(o.Dur) {
		var ret []CreateTeamCollectionsRequestDatasetsInner
		return ret
	}
	return o.Dur
}

// GetDurOk returns a tuple with the Dur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetDurOk() ([]CreateTeamCollectionsRequestDatasetsInner, bool) {
	if o == nil || IsNil(o.Dur) {
		return nil, false
	}
	return o.Dur, true
}

// HasDur returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasDur() bool {
	if o != nil && !IsNil(o.Dur) {
		return true
	}

	return false
}

// SetDur gets a reference to the given []CreateTeamCollectionsRequestDatasetsInner and assigns it to the Dur field.
func (o *CreateTeamCollectionsRequest) SetDur(v []CreateTeamCollectionsRequestDatasetsInner) {
	o.Dur = v
}

// GetPublications returns the Publications field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetPublications() []CreateTeamCollectionsRequestDatasetsInner {
	if o == nil || IsNil(o.Publications) {
		var ret []CreateTeamCollectionsRequestDatasetsInner
		return ret
	}
	return o.Publications
}

// GetPublicationsOk returns a tuple with the Publications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetPublicationsOk() ([]CreateTeamCollectionsRequestDatasetsInner, bool) {
	if o == nil || IsNil(o.Publications) {
		return nil, false
	}
	return o.Publications, true
}

// HasPublications returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasPublications() bool {
	if o != nil && !IsNil(o.Publications) {
		return true
	}

	return false
}

// SetPublications gets a reference to the given []CreateTeamCollectionsRequestDatasetsInner and assigns it to the Publications field.
func (o *CreateTeamCollectionsRequest) SetPublications(v []CreateTeamCollectionsRequestDatasetsInner) {
	o.Publications = v
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *CreateTeamCollectionsRequest) GetPublic() bool {
	if o == nil || IsNil(o.Public) {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTeamCollectionsRequest) GetPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *CreateTeamCollectionsRequest) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *CreateTeamCollectionsRequest) SetPublic(v bool) {
	o.Public = &v
}

func (o CreateTeamCollectionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTeamCollectionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageLink) {
		toSerialize["image_link"] = o.ImageLink
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	if !IsNil(o.Datasets) {
		toSerialize["datasets"] = o.Datasets
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	if !IsNil(o.Dur) {
		toSerialize["dur"] = o.Dur
	}
	if !IsNil(o.Publications) {
		toSerialize["publications"] = o.Publications
	}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	return toSerialize, nil
}

type NullableCreateTeamCollectionsRequest struct {
	value *CreateTeamCollectionsRequest
	isSet bool
}

func (v NullableCreateTeamCollectionsRequest) Get() *CreateTeamCollectionsRequest {
	return v.value
}

func (v *NullableCreateTeamCollectionsRequest) Set(val *CreateTeamCollectionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTeamCollectionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTeamCollectionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTeamCollectionsRequest(val *CreateTeamCollectionsRequest) *NullableCreateTeamCollectionsRequest {
	return &NullableCreateTeamCollectionsRequest{value: val, isSet: true}
}

func (v NullableCreateTeamCollectionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTeamCollectionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


