/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the FetchAllReviews200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchAllReviews200Response{}

// FetchAllReviews200Response struct for FetchAllReviews200Response
type FetchAllReviews200Response struct {
	Message *string `json:"message,omitempty"`
	Data []FetchAllReviews200ResponseDataInner `json:"data,omitempty"`
}

// NewFetchAllReviews200Response instantiates a new FetchAllReviews200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchAllReviews200Response() *FetchAllReviews200Response {
	this := FetchAllReviews200Response{}
	return &this
}

// NewFetchAllReviews200ResponseWithDefaults instantiates a new FetchAllReviews200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchAllReviews200ResponseWithDefaults() *FetchAllReviews200Response {
	this := FetchAllReviews200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FetchAllReviews200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FetchAllReviews200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FetchAllReviews200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FetchAllReviews200Response) GetData() []FetchAllReviews200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []FetchAllReviews200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchAllReviews200Response) GetDataOk() ([]FetchAllReviews200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FetchAllReviews200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []FetchAllReviews200ResponseDataInner and assigns it to the Data field.
func (o *FetchAllReviews200Response) SetData(v []FetchAllReviews200ResponseDataInner) {
	o.Data = v
}

func (o FetchAllReviews200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchAllReviews200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFetchAllReviews200Response struct {
	value *FetchAllReviews200Response
	isSet bool
}

func (v NullableFetchAllReviews200Response) Get() *FetchAllReviews200Response {
	return v.value
}

func (v *NullableFetchAllReviews200Response) Set(val *FetchAllReviews200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchAllReviews200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchAllReviews200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchAllReviews200Response(val *FetchAllReviews200Response) *NullableFetchAllReviews200Response {
	return &NullableFetchAllReviews200Response{value: val, isSet: true}
}

func (v NullableFetchAllReviews200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchAllReviews200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


