/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDataProviderCollRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDataProviderCollRequest{}

// CreateDataProviderCollRequest struct for CreateDataProviderCollRequest
type CreateDataProviderCollRequest struct {
	Name string `json:"name"`
	Summary string `json:"summary"`
	Enabled bool `json:"enabled"`
	Service *string `json:"service,omitempty"`
	TeamIds []int32 `json:"team_ids"`
}

type _CreateDataProviderCollRequest CreateDataProviderCollRequest

// NewCreateDataProviderCollRequest instantiates a new CreateDataProviderCollRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDataProviderCollRequest(name string, summary string, enabled bool, teamIds []int32) *CreateDataProviderCollRequest {
	this := CreateDataProviderCollRequest{}
	this.Name = name
	this.Summary = summary
	this.Enabled = enabled
	this.TeamIds = teamIds
	return &this
}

// NewCreateDataProviderCollRequestWithDefaults instantiates a new CreateDataProviderCollRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDataProviderCollRequestWithDefaults() *CreateDataProviderCollRequest {
	this := CreateDataProviderCollRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateDataProviderCollRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDataProviderCollRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDataProviderCollRequest) SetName(v string) {
	o.Name = v
}

// GetSummary returns the Summary field value
func (o *CreateDataProviderCollRequest) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *CreateDataProviderCollRequest) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *CreateDataProviderCollRequest) SetSummary(v string) {
	o.Summary = v
}

// GetEnabled returns the Enabled field value
func (o *CreateDataProviderCollRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreateDataProviderCollRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CreateDataProviderCollRequest) SetEnabled(v bool) {
	o.Enabled = v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *CreateDataProviderCollRequest) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDataProviderCollRequest) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *CreateDataProviderCollRequest) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *CreateDataProviderCollRequest) SetService(v string) {
	o.Service = &v
}

// GetTeamIds returns the TeamIds field value
func (o *CreateDataProviderCollRequest) GetTeamIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.TeamIds
}

// GetTeamIdsOk returns a tuple with the TeamIds field value
// and a boolean to check if the value has been set.
func (o *CreateDataProviderCollRequest) GetTeamIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TeamIds, true
}

// SetTeamIds sets field value
func (o *CreateDataProviderCollRequest) SetTeamIds(v []int32) {
	o.TeamIds = v
}

func (o CreateDataProviderCollRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDataProviderCollRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["summary"] = o.Summary
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	toSerialize["team_ids"] = o.TeamIds
	return toSerialize, nil
}

func (o *CreateDataProviderCollRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"summary",
		"enabled",
		"team_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDataProviderCollRequest := _CreateDataProviderCollRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDataProviderCollRequest)

	if err != nil {
		return err
	}

	*o = CreateDataProviderCollRequest(varCreateDataProviderCollRequest)

	return err
}

type NullableCreateDataProviderCollRequest struct {
	value *CreateDataProviderCollRequest
	isSet bool
}

func (v NullableCreateDataProviderCollRequest) Get() *CreateDataProviderCollRequest {
	return v.value
}

func (v *NullableCreateDataProviderCollRequest) Set(val *CreateDataProviderCollRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDataProviderCollRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDataProviderCollRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDataProviderCollRequest(val *CreateDataProviderCollRequest) *NullableCreateDataProviderCollRequest {
	return &NullableCreateDataProviderCollRequest{value: val, isSet: true}
}

func (v NullableCreateDataProviderCollRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDataProviderCollRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


