/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
	"time"
)

// checks if the ListLibraries200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLibraries200ResponseDataInner{}

// ListLibraries200ResponseDataInner struct for ListLibraries200ResponseDataInner
type ListLibraries200ResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UserId *int32 `json:"user_id,omitempty"`
	DatasetId *string `json:"dataset_id,omitempty"`
	DatasetStatus *string `json:"dataset_status,omitempty"`
	DataProviderId *string `json:"data_provider_id,omitempty"`
	DataProviderDarStatus *bool `json:"data_provider_dar_status,omitempty"`
	DataProviderName *string `json:"data_provider_name,omitempty"`
}

// NewListLibraries200ResponseDataInner instantiates a new ListLibraries200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLibraries200ResponseDataInner() *ListLibraries200ResponseDataInner {
	this := ListLibraries200ResponseDataInner{}
	return &this
}

// NewListLibraries200ResponseDataInnerWithDefaults instantiates a new ListLibraries200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLibraries200ResponseDataInnerWithDefaults() *ListLibraries200ResponseDataInner {
	this := ListLibraries200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ListLibraries200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ListLibraries200ResponseDataInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ListLibraries200ResponseDataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *ListLibraries200ResponseDataInner) SetUserId(v int32) {
	o.UserId = &v
}

// GetDatasetId returns the DatasetId field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetDatasetId() string {
	if o == nil || IsNil(o.DatasetId) {
		var ret string
		return ret
	}
	return *o.DatasetId
}

// GetDatasetIdOk returns a tuple with the DatasetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetDatasetIdOk() (*string, bool) {
	if o == nil || IsNil(o.DatasetId) {
		return nil, false
	}
	return o.DatasetId, true
}

// HasDatasetId returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasDatasetId() bool {
	if o != nil && !IsNil(o.DatasetId) {
		return true
	}

	return false
}

// SetDatasetId gets a reference to the given string and assigns it to the DatasetId field.
func (o *ListLibraries200ResponseDataInner) SetDatasetId(v string) {
	o.DatasetId = &v
}

// GetDatasetStatus returns the DatasetStatus field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetDatasetStatus() string {
	if o == nil || IsNil(o.DatasetStatus) {
		var ret string
		return ret
	}
	return *o.DatasetStatus
}

// GetDatasetStatusOk returns a tuple with the DatasetStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetDatasetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DatasetStatus) {
		return nil, false
	}
	return o.DatasetStatus, true
}

// HasDatasetStatus returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasDatasetStatus() bool {
	if o != nil && !IsNil(o.DatasetStatus) {
		return true
	}

	return false
}

// SetDatasetStatus gets a reference to the given string and assigns it to the DatasetStatus field.
func (o *ListLibraries200ResponseDataInner) SetDatasetStatus(v string) {
	o.DatasetStatus = &v
}

// GetDataProviderId returns the DataProviderId field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetDataProviderId() string {
	if o == nil || IsNil(o.DataProviderId) {
		var ret string
		return ret
	}
	return *o.DataProviderId
}

// GetDataProviderIdOk returns a tuple with the DataProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetDataProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.DataProviderId) {
		return nil, false
	}
	return o.DataProviderId, true
}

// HasDataProviderId returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasDataProviderId() bool {
	if o != nil && !IsNil(o.DataProviderId) {
		return true
	}

	return false
}

// SetDataProviderId gets a reference to the given string and assigns it to the DataProviderId field.
func (o *ListLibraries200ResponseDataInner) SetDataProviderId(v string) {
	o.DataProviderId = &v
}

// GetDataProviderDarStatus returns the DataProviderDarStatus field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetDataProviderDarStatus() bool {
	if o == nil || IsNil(o.DataProviderDarStatus) {
		var ret bool
		return ret
	}
	return *o.DataProviderDarStatus
}

// GetDataProviderDarStatusOk returns a tuple with the DataProviderDarStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetDataProviderDarStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.DataProviderDarStatus) {
		return nil, false
	}
	return o.DataProviderDarStatus, true
}

// HasDataProviderDarStatus returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasDataProviderDarStatus() bool {
	if o != nil && !IsNil(o.DataProviderDarStatus) {
		return true
	}

	return false
}

// SetDataProviderDarStatus gets a reference to the given bool and assigns it to the DataProviderDarStatus field.
func (o *ListLibraries200ResponseDataInner) SetDataProviderDarStatus(v bool) {
	o.DataProviderDarStatus = &v
}

// GetDataProviderName returns the DataProviderName field value if set, zero value otherwise.
func (o *ListLibraries200ResponseDataInner) GetDataProviderName() string {
	if o == nil || IsNil(o.DataProviderName) {
		var ret string
		return ret
	}
	return *o.DataProviderName
}

// GetDataProviderNameOk returns a tuple with the DataProviderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLibraries200ResponseDataInner) GetDataProviderNameOk() (*string, bool) {
	if o == nil || IsNil(o.DataProviderName) {
		return nil, false
	}
	return o.DataProviderName, true
}

// HasDataProviderName returns a boolean if a field has been set.
func (o *ListLibraries200ResponseDataInner) HasDataProviderName() bool {
	if o != nil && !IsNil(o.DataProviderName) {
		return true
	}

	return false
}

// SetDataProviderName gets a reference to the given string and assigns it to the DataProviderName field.
func (o *ListLibraries200ResponseDataInner) SetDataProviderName(v string) {
	o.DataProviderName = &v
}

func (o ListLibraries200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLibraries200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.DatasetId) {
		toSerialize["dataset_id"] = o.DatasetId
	}
	if !IsNil(o.DatasetStatus) {
		toSerialize["dataset_status"] = o.DatasetStatus
	}
	if !IsNil(o.DataProviderId) {
		toSerialize["data_provider_id"] = o.DataProviderId
	}
	if !IsNil(o.DataProviderDarStatus) {
		toSerialize["data_provider_dar_status"] = o.DataProviderDarStatus
	}
	if !IsNil(o.DataProviderName) {
		toSerialize["data_provider_name"] = o.DataProviderName
	}
	return toSerialize, nil
}

type NullableListLibraries200ResponseDataInner struct {
	value *ListLibraries200ResponseDataInner
	isSet bool
}

func (v NullableListLibraries200ResponseDataInner) Get() *ListLibraries200ResponseDataInner {
	return v.value
}

func (v *NullableListLibraries200ResponseDataInner) Set(val *ListLibraries200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListLibraries200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListLibraries200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLibraries200ResponseDataInner(val *ListLibraries200ResponseDataInner) *NullableListLibraries200ResponseDataInner {
	return &NullableListLibraries200ResponseDataInner{value: val, isSet: true}
}

func (v NullableListLibraries200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLibraries200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


