/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the WidgetAnalytics200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WidgetAnalytics200Response{}

// WidgetAnalytics200Response struct for WidgetAnalytics200Response
type WidgetAnalytics200Response struct {
	ByEvent []map[string]interface{} `json:"by_event,omitempty"`
	ByWidget []map[string]interface{} `json:"by_widget,omitempty"`
	OverTime []map[string]interface{} `json:"over_time,omitempty"`
}

// NewWidgetAnalytics200Response instantiates a new WidgetAnalytics200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWidgetAnalytics200Response() *WidgetAnalytics200Response {
	this := WidgetAnalytics200Response{}
	return &this
}

// NewWidgetAnalytics200ResponseWithDefaults instantiates a new WidgetAnalytics200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWidgetAnalytics200ResponseWithDefaults() *WidgetAnalytics200Response {
	this := WidgetAnalytics200Response{}
	return &this
}

// GetByEvent returns the ByEvent field value if set, zero value otherwise.
func (o *WidgetAnalytics200Response) GetByEvent() []map[string]interface{} {
	if o == nil || IsNil(o.ByEvent) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ByEvent
}

// GetByEventOk returns a tuple with the ByEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetAnalytics200Response) GetByEventOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ByEvent) {
		return nil, false
	}
	return o.ByEvent, true
}

// HasByEvent returns a boolean if a field has been set.
func (o *WidgetAnalytics200Response) HasByEvent() bool {
	if o != nil && !IsNil(o.ByEvent) {
		return true
	}

	return false
}

// SetByEvent gets a reference to the given []map[string]interface{} and assigns it to the ByEvent field.
func (o *WidgetAnalytics200Response) SetByEvent(v []map[string]interface{}) {
	o.ByEvent = v
}

// GetByWidget returns the ByWidget field value if set, zero value otherwise.
func (o *WidgetAnalytics200Response) GetByWidget() []map[string]interface{} {
	if o == nil || IsNil(o.ByWidget) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ByWidget
}

// GetByWidgetOk returns a tuple with the ByWidget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetAnalytics200Response) GetByWidgetOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ByWidget) {
		return nil, false
	}
	return o.ByWidget, true
}

// HasByWidget returns a boolean if a field has been set.
func (o *WidgetAnalytics200Response) HasByWidget() bool {
	if o != nil && !IsNil(o.ByWidget) {
		return true
	}

	return false
}

// SetByWidget gets a reference to the given []map[string]interface{} and assigns it to the ByWidget field.
func (o *WidgetAnalytics200Response) SetByWidget(v []map[string]interface{}) {
	o.ByWidget = v
}

// GetOverTime returns the OverTime field value if set, zero value otherwise.
func (o *WidgetAnalytics200Response) GetOverTime() []map[string]interface{} {
	if o == nil || IsNil(o.OverTime) {
		var ret []map[string]interface{}
		return ret
	}
	return o.OverTime
}

// GetOverTimeOk returns a tuple with the OverTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetAnalytics200Response) GetOverTimeOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.OverTime) {
		return nil, false
	}
	return o.OverTime, true
}

// HasOverTime returns a boolean if a field has been set.
func (o *WidgetAnalytics200Response) HasOverTime() bool {
	if o != nil && !IsNil(o.OverTime) {
		return true
	}

	return false
}

// SetOverTime gets a reference to the given []map[string]interface{} and assigns it to the OverTime field.
func (o *WidgetAnalytics200Response) SetOverTime(v []map[string]interface{}) {
	o.OverTime = v
}

func (o WidgetAnalytics200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WidgetAnalytics200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ByEvent) {
		toSerialize["by_event"] = o.ByEvent
	}
	if !IsNil(o.ByWidget) {
		toSerialize["by_widget"] = o.ByWidget
	}
	if !IsNil(o.OverTime) {
		toSerialize["over_time"] = o.OverTime
	}
	return toSerialize, nil
}

type NullableWidgetAnalytics200Response struct {
	value *WidgetAnalytics200Response
	isSet bool
}

func (v NullableWidgetAnalytics200Response) Get() *WidgetAnalytics200Response {
	return v.value
}

func (v *NullableWidgetAnalytics200Response) Set(val *WidgetAnalytics200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWidgetAnalytics200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWidgetAnalytics200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWidgetAnalytics200Response(val *WidgetAnalytics200Response) *NullableWidgetAnalytics200Response {
	return &NullableWidgetAnalytics200Response{value: val, isSet: true}
}

func (v NullableWidgetAnalytics200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWidgetAnalytics200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


