/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the SearchPublicationsByDoi200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchPublicationsByDoi200Response{}

// SearchPublicationsByDoi200Response struct for SearchPublicationsByDoi200Response
type SearchPublicationsByDoi200Response struct {
	Data []interface{} `json:"data,omitempty"`
}

// NewSearchPublicationsByDoi200Response instantiates a new SearchPublicationsByDoi200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchPublicationsByDoi200Response() *SearchPublicationsByDoi200Response {
	this := SearchPublicationsByDoi200Response{}
	return &this
}

// NewSearchPublicationsByDoi200ResponseWithDefaults instantiates a new SearchPublicationsByDoi200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchPublicationsByDoi200ResponseWithDefaults() *SearchPublicationsByDoi200Response {
	this := SearchPublicationsByDoi200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SearchPublicationsByDoi200Response) GetData() []interface{} {
	if o == nil || IsNil(o.Data) {
		var ret []interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchPublicationsByDoi200Response) GetDataOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SearchPublicationsByDoi200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []interface{} and assigns it to the Data field.
func (o *SearchPublicationsByDoi200Response) SetData(v []interface{}) {
	o.Data = v
}

func (o SearchPublicationsByDoi200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchPublicationsByDoi200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSearchPublicationsByDoi200Response struct {
	value *SearchPublicationsByDoi200Response
	isSet bool
}

func (v NullableSearchPublicationsByDoi200Response) Get() *SearchPublicationsByDoi200Response {
	return v.value
}

func (v *NullableSearchPublicationsByDoi200Response) Set(val *SearchPublicationsByDoi200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchPublicationsByDoi200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchPublicationsByDoi200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchPublicationsByDoi200Response(val *SearchPublicationsByDoi200Response) *NullableSearchPublicationsByDoi200Response {
	return &NullableSearchPublicationsByDoi200Response{value: val, isSet: true}
}

func (v NullableSearchPublicationsByDoi200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchPublicationsByDoi200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


