/*
HDRUK Gateway API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gatewayapisdk

import (
	"encoding/json"
)

// checks if the SearchDataUsesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchDataUsesRequest{}

// SearchDataUsesRequest struct for SearchDataUsesRequest
type SearchDataUsesRequest struct {
	Query *string `json:"query,omitempty"`
}

// NewSearchDataUsesRequest instantiates a new SearchDataUsesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchDataUsesRequest() *SearchDataUsesRequest {
	this := SearchDataUsesRequest{}
	return &this
}

// NewSearchDataUsesRequestWithDefaults instantiates a new SearchDataUsesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchDataUsesRequestWithDefaults() *SearchDataUsesRequest {
	this := SearchDataUsesRequest{}
	return &this
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *SearchDataUsesRequest) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataUsesRequest) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *SearchDataUsesRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *SearchDataUsesRequest) SetQuery(v string) {
	o.Query = &v
}

func (o SearchDataUsesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchDataUsesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableSearchDataUsesRequest struct {
	value *SearchDataUsesRequest
	isSet bool
}

func (v NullableSearchDataUsesRequest) Get() *SearchDataUsesRequest {
	return v.value
}

func (v *NullableSearchDataUsesRequest) Set(val *SearchDataUsesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchDataUsesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchDataUsesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchDataUsesRequest(val *SearchDataUsesRequest) *NullableSearchDataUsesRequest {
	return &NullableSearchDataUsesRequest{value: val, isSet: true}
}

func (v NullableSearchDataUsesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchDataUsesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


